'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import {adminApprovePartnerApplication,adminSetPartnerApplicationStatus,loadAdminPartnerApplications} from '@/lib/data';import {Section,Status} from './ui';
export function AdminPartnerApplications(){
 const [rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(),[notes,setNotes]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>loadAdminPartnerApplications().then(r=>{setRows(r.data);if(r.error)setMessage(r.error.message)});
 useEffect(()=>{void load()},[]);
 const act=async(label:string,fn:()=>Promise<any>)=>{if(!selected)return;setBusy(true);setMessage('');const r=await fn();setBusy(false);if(r.error)return setMessage(r.error.message);setMessage(label);await load();setSelected(undefined)};
 return <div className="applications-layout"><Section title="Applications">{rows.map(x=><button className="application-row" key={x.id} onClick={()=>{setSelected(x);setNotes(x.admin_notes||'')}}><span><b>{x.org_name}</b><small>{x.application_type} · {x.country_name||x.other_country_text||'Country pending'}</small></span><Status value={String(x.status).replace('_',' ').toUpperCase()}/></button>)}{!rows.length&&<div className="empty-state">No applications.</div>}</Section>
 {selected&&<Section title={selected.org_name}><div className="application-detail"><p><b>Type:</b> {selected.application_type}</p><p><b>Submitted:</b> {new Date(selected.created_at).toLocaleString()}</p><p><b>Contact:</b> {selected.contact_name||'—'} · {selected.email||selected.telephone||selected.mobile||'—'}</p><p><b>Website:</b> {selected.website||'—'}</p><p><b>{selected.application_type==='operator'?'Transport type':'Destination type'}:</b> {selected.transport_type_name||selected.destination_type_name}</p><p><b>Description:</b> {selected.description||'—'}</p><p><b>Suggested pickups:</b> {selected.pickup_suggestions||'—'}</p><p><b>Suggested destinations:</b> {selected.destination_suggestions||'—'}</p><label>Site Admin notes<textarea name="admin_notes" value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="action-buttons"><button className="btn secondary" disabled={busy} onClick={()=>act('Marked under review',()=>adminSetPartnerApplicationStatus(selected.id,'under_review',notes))}>Under review</button><button className="btn danger" disabled={busy} onClick={()=>act('Application rejected',()=>adminSetPartnerApplicationStatus(selected.id,'rejected',notes))}>Reject</button><button className="btn" disabled={busy||selected.status==='approved'} onClick={()=>act('Application approved',()=>adminApprovePartnerApplication(selected.id))}>Approve</button></div>{selected.operator_id&&<Link href={'/admin/operators/'+selected.operator_id}>Open approved operator</Link>}{selected.destination_id&&<Link href="/admin/network">Complete destination draft and publish</Link>}</div></Section>}
 {message&&<p className="data-note">{message}</p>}</div>
}
