'use client';

import React,{useEffect,useMemo,useRef,useState} from 'react';
import {captainBroadcastToParties,captainCompleteJourney,captainReplyToParty,captainStartJourney,loadCaptainJourneyConversations,loadCaptainJourneyMessages,loadCaptainJourneyMessageWindows,markJourneyConversationRead,loadCaptainManifest,loadCaptainMyJourneys} from '@/lib/data';
import {KpiCard,Section,Status} from './ui';
import {JourneyConversation} from './journey-conversation';
import {CaptainBroadcastComposer} from './captain-broadcast-composer';

const when=(value:any)=>value?new Date(value).toLocaleString([],{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const norm=(value:any)=>String(value||'').toLowerCase();
const windowState=(conversation:any)=>conversation?.messaging_window_open?'open' as const:(conversation?.messaging_opens_at&&new Date(conversation.messaging_opens_at).getTime()>Date.now()?'scheduled' as const:'closed' as const);

type DashboardResult<T=any>={data:T;error:any};
type RowsLoader=()=>Promise<DashboardResult<any[]|null>>;
export type CaptainDashboardLoaders={journeys:RowsLoader;manifest:RowsLoader;conversations:RowsLoader;messages:RowsLoader;windows:RowsLoader};
export type CaptainDashboardActions={
 markRead:(conversationId:string,audience:'captain')=>Promise<DashboardResult>;
 broadcast:(allocationId:string,message:string,category:string,requestId:string)=>Promise<DashboardResult>;
 complete:(assignmentId:string,normal:boolean,notes:string,incident:boolean,summary:string)=>Promise<DashboardResult>;
 reply:(conversationId:string,message:string,category:string)=>Promise<DashboardResult>;
 start:(assignmentId:string)=>Promise<DashboardResult>;
};
export const defaultCaptainDashboardLoaders:CaptainDashboardLoaders={journeys:loadCaptainMyJourneys,manifest:loadCaptainManifest,conversations:loadCaptainJourneyConversations,messages:loadCaptainJourneyMessages,windows:loadCaptainJourneyMessageWindows};
export const defaultCaptainDashboardActions:CaptainDashboardActions={markRead:markJourneyConversationRead,broadcast:captainBroadcastToParties,complete:captainCompleteJourney,reply:captainReplyToParty,start:captainStartJourney};

function useRows(fn:RowsLoader){
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState('');
 const request=useRef(0);
 const reload=async(current:()=>boolean=()=>true)=>{const id=++request.current;try{const result=await fn();if(id!==request.current||!current())return;setRows(result.data||[]);setError(result.error?.message||'')}catch(reason:any){if(id!==request.current||!current())return;setRows([]);setError(reason?.message||String(reason))}};
 useEffect(()=>{void reload();return()=>{request.current++}},[fn]);
 return {rows,error,reload};
}

export function CaptainDashboard({loaders=defaultCaptainDashboardLoaders,actions=defaultCaptainDashboardActions}:{loaders?:CaptainDashboardLoaders;actions?:CaptainDashboardActions}={}){
 const journeys=useRows(loaders.journeys),manifest=useRows(loaders.manifest),conversations=useRows(loaders.conversations),messages=useRows(loaders.messages),windows=useRows(loaders.windows);
 const [selectedId,setSelectedId]=useState(''),[selectedConversationId,setSelectedConversationId]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
 const contextOperation=useRef(0),refreshRequest=useRef(0);
 const selected=useMemo(()=>selectedId?journeys.rows.find(row=>(row.captain_assignment_id||row.confirmed_allocation_id)===selectedId):journeys.rows.find(row=>row.actual_departure_ts&&!row.actual_arrival_ts)||journeys.rows.find(row=>norm(row.departure_status)==='confirmed')||journeys.rows[0],[journeys.rows,selectedId]);
 const selectedKey=selected?.captain_assignment_id||selected?.confirmed_allocation_id;
 const parties=selected?conversations.rows.filter(row=>row.confirmed_allocation_id===selected.confirmed_allocation_id):[];
 const activeParty=parties.find(row=>row.id===selectedConversationId)||parties[0];
 const partyMessages=activeParty?messages.rows.filter(row=>row.conversation_id===activeParty.id):[];
 useEffect(()=>{let cancelled=false;if(!activeParty||!Number(activeParty.unread_count||0))return;void (async()=>{try{const result=await actions.markRead(activeParty.id,'captain');if(!cancelled&&!result.error)await conversations.reload(()=>!cancelled)}catch{}})();return()=>{cancelled=true}},[actions,activeParty?.id,activeParty?.unread_count,partyMessages.length]);
 const pax=selected?manifest.rows.filter(row=>row.captain_assignment_id===selected.captain_assignment_id||row.confirmed_allocation_id===selected.confirmed_allocation_id):[];
 const selectedWindow=windows.rows.find(row=>row.confirmed_allocation_id===selected?.confirmed_allocation_id);
 const ready=journeys.rows.filter(row=>!row.actual_departure_ts&&norm(row.departure_status)==='confirmed').length,active=journeys.rows.filter(row=>row.actual_departure_ts&&!row.actual_arrival_ts).length,unread=conversations.rows.reduce((total,row)=>total+Number(row.unread_count||0),0),broadcastOpen=windowState(selectedWindow)==='open';
 const refresh=async()=>{const id=++refreshRequest.current,current=()=>id===refreshRequest.current;await Promise.all([journeys.reload(current),manifest.reload(current),conversations.reload(current),messages.reload(current),windows.reload(current)])};
 const invalidateSelection=()=>{contextOperation.current++;setBusy('');setNotice('')};
 const run=async(label:string,action:()=>Promise<any>)=>{const id=++contextOperation.current;setBusy(label);setNotice('');let result;try{result=await action()}catch(reason:any){if(id===contextOperation.current){setBusy('');setNotice(reason?.message||String(reason))}return}if(result.error){if(id===contextOperation.current){setBusy('');setNotice(result.error.message||String(result.error))}return}await refresh();if(id===contextOperation.current){setNotice(`${label} completed`);setBusy('')}};
 const start=async()=>{if(selected?.captain_assignment_id&&window.confirm(`Start ${selected.route_name} now? This records the actual departure time.`))await run('Journey start',()=>actions.start(selected.captain_assignment_id))};
 const complete=async()=>{if(!selected?.captain_assignment_id)return;const notes=window.prompt('Voyage / journey notes','')??'';const normal=window.confirm('Did the journey complete normally? Choose Cancel for an abnormal completion.');const incident=!normal||window.confirm('Was there an incident worth recording?');const summary=incident?(window.prompt('Incident / abnormal completion summary','')||'Abnormal completion'):'';if(window.confirm('Complete this journey and record the actual arrival time?'))await run('Journey completion',()=>actions.complete(selected.captain_assignment_id,normal,notes,incident,summary))};
 const reply=async(message:string,category:string)=>{if(!activeParty)return;const id=++contextOperation.current;setBusy('Party reply');setNotice('');let result;try{result=await actions.reply(activeParty.id,message,category)}catch(reason:any){if(id===contextOperation.current){setBusy('');setNotice(reason?.message||String(reason))}throw reason}if(result.error){if(id===contextOperation.current){setBusy('');setNotice(result.error.message||String(result.error))}throw result.error}await refresh();if(id===contextOperation.current){setNotice('Party reply completed');setBusy('')}};
 const sendBroadcast=async(message:string,category:string,requestId:string)=>{if(!selected?.confirmed_allocation_id)return;const id=++contextOperation.current;setBusy('Passenger update');setNotice('');let result;try{result=await actions.broadcast(selected.confirmed_allocation_id,message,category,requestId)}catch(reason:any){if(id===contextOperation.current){setBusy('');setNotice(reason?.message||String(reason))}throw reason}if(result.error){if(id===contextOperation.current){setBusy('');setNotice(result.error.message||String(result.error))}throw result.error}await refresh();if(id===contextOperation.current){setNotice('Passenger update completed');setBusy('')}};
 return <>
  <div className="grid-4"><KpiCard label="Assigned journeys" value={String(journeys.rows.length)}/><KpiCard label="Ready to start" value={String(ready)}/><KpiCard label="In progress" value={String(active)}/><KpiCard label="Unread party messages" value={String(unread)}/></div>
  <div className="grid-2" style={{marginTop:12}}><Section title="My journeys">{journeys.rows.map(row=>{const key=row.captain_assignment_id||row.confirmed_allocation_id,state=row.actual_arrival_ts?'COMPLETED':row.actual_departure_ts?'ACTIVE':String(row.departure_status||'ASSIGNED').toUpperCase(),count=conversations.rows.filter(item=>item.confirmed_allocation_id===row.confirmed_allocation_id).reduce((total,item)=>total+Number(item.unread_count||0),0);return <button className={`support-item ${selectedKey===key?'selected':''}`} key={key} onClick={()=>{invalidateSelection();setSelectedId(key);setSelectedConversationId('')}}><span><b>{row.route_name}</b><small>{when(row.scheduled_departure_ts)} · {row.vehicle_name} · {row.operator_name}</small></span><span><Status value={state}/>{count>0?<small className="unread-badge">Unread {count}</small>:null}</span></button>})}{!journeys.rows.length?<div className="empty-state">No captain journeys are linked to this signed-in account yet.</div>:null}</Section><Section title="Journey control">{selected?<><div className="notice"><span><b>{selected.route_name}</b><br/><small>{selected.vehicle_name} · {when(selected.scheduled_departure_ts)}</small></span><Status value={selected.actual_arrival_ts?'COMPLETED':selected.actual_departure_ts?'ACTIVE':String(selected.departure_status||'ASSIGNED').toUpperCase()}/></div><div className="grid-2" style={{marginTop:10}}><div className="mini-metric"><small>Scheduled departure</small><strong>{when(selected.scheduled_departure_ts)}</strong></div><div className="mini-metric"><small>Passengers</small><strong>{pax.length||selected.booked_seats||0}</strong></div></div><div className="action-buttons" style={{marginTop:12}}>{!selected.actual_departure_ts&&norm(selected.departure_status)==='confirmed'?<button className="btn" disabled={Boolean(busy)} onClick={start}>Start journey</button>:null}{selected.actual_departure_ts&&!selected.actual_arrival_ts?<button className="btn" disabled={Boolean(busy)} onClick={complete}>Complete journey</button>:null}</div>{selected.actual_departure_ts?<div className="notice" style={{marginTop:12}}><span>Actual departure</span><b>{when(selected.actual_departure_ts)}</b></div>:null}{selected.actual_arrival_ts?<div className="notice"><span>Actual arrival</span><b>{when(selected.actual_arrival_ts)}</b></div>:null}</>:<div className="empty-state">Select a journey.</div>}{notice?<p className={notice.includes('completed')?'action-success':'action-error'}>{notice}</p>:null}</Section></div>
  <div className="grid-2" style={{marginTop:12}}><Section title="Passenger manifest">{pax.map((person:any)=><div className="notice" key={person.passenger_id||`${person.booking_id}-${person.passenger_first_name}`}><span><b>{person.passenger_first_name||person.customer_name} {person.passenger_last_name||''}</b><br/><small>{person.age_group||'Passenger'} · party of {person.booking_party_size||1}</small></span><span><Status value={String(person.booking_status||'BOOKED').toUpperCase()}/><br/><small>{person.special_requirements||person.notes||''}</small></span></div>)}{selected&&!pax.length?<div className="empty-state">No passengers are currently allocated to this journey.</div>:null}{!selected?<div className="empty-state">Select a journey to view its manifest.</div>:null}</Section><Section title="Party conversations">{selected?<>{parties.map((party,index)=>{const state=windowState(party),count=Number(party.unread_count||0);return <button aria-label={`Open party ${index+1} conversation`} className={`support-item ${activeParty?.id===party.id?'selected':''}`} key={party.id} onClick={()=>{invalidateSelection();setSelectedConversationId(party.id)}}><span><b>Party {index+1}</b><small>Private conversation · {state}</small></span><span>{count>0?<small className="unread-badge">Unread {count}</small>:null}<Status value={state.toUpperCase()}/></span></button>})}{activeParty?<JourneyConversation key={activeParty.id} threadId={activeParty.id} mode="captain" windowState={windowState(activeParty)} closesAt={activeParty.messaging_closes_at} messages={partyMessages} busy={Boolean(busy)} onSend={reply}/>:<div className="empty-state">No private party conversations yet.</div>}</>:<div className="empty-state">Select a journey to view private party conversations.</div>}</Section></div>
  <Section title="Message all parties">{selected?<CaptainBroadcastComposer key={selected.confirmed_allocation_id} allocationId={selected.confirmed_allocation_id} open={broadcastOpen} busy={Boolean(busy)} onSend={sendBroadcast}/>:<div className="empty-state">Select a journey to message its parties.</div>}</Section>
  <Section title="Captain operating rules"><div className="grid-3"><div className="mini-metric"><small>Before departure</small><strong>Review manifest</strong><p className="data-note">Check the assigned vehicle, scheduled time and passenger list before starting.</p></div><div className="mini-metric"><small>During disruption</small><strong>Message parties</strong><p className="data-note">Send a private reply or a journey-wide operational update from this dashboard.</p></div><div className="mini-metric"><small>After arrival</small><strong>Complete journey</strong><p className="data-note">Actual arrival and voyage notes become part of the operational audit and settlement evidence.</p></div></div></Section>
  {(journeys.error||manifest.error||conversations.error||messages.error||windows.error)?<p className="action-error">{journeys.error||manifest.error||conversations.error||messages.error||windows.error}</p>:null}
 </>;
}
