'use client';

import React,{useEffect,useMemo,useRef,useState} from 'react';
import {captainBroadcastToParties,captainCompleteJourney,captainEndLeg,captainOpenPartyConversation,captainReplyToParty,captainStartJourney,captainStartLeg,loadCaptainJourneyConversations,loadCaptainJourneyMessages,loadCaptainJourneyMessageWindows,markJourneyConversationRead,loadCaptainManifest,loadCaptainMyJourneys,loadCaptainTodayDuties,loadCaptainTodayManifest} from '@/lib/data';
import {selectCurrentDuty} from '@/lib/captain-today';
import {JourneyConversation} from './journey-conversation';
import {CaptainBroadcastComposer} from './captain-broadcast-composer';
import {CaptainToday,type CaptainTodayActions,type CaptainTodayDutyRow,type CaptainTodayManifestRow,type CaptainTodayReloadRequest,type CaptainTodayReloadResult} from './captain-today';
import {CaptainGeneral} from './captain-general';
import {CaptainWorkspaceTabs,captainWorkspaceTab,type CaptainWorkspaceTab} from './captain-workspace-tabs';

type DashboardResult<T=any>={data:T;error:any};
type RowsLoader=()=>Promise<DashboardResult<any[]|null>>;
type PartyIntent={dutyId:string;allocationId:string;bookingId:string};
export type CaptainDashboardLoaders={journeys:RowsLoader;manifest:RowsLoader;conversations:RowsLoader;messages:RowsLoader;windows:RowsLoader;todayDuties?:RowsLoader;todayManifest?:RowsLoader};
export type CaptainDashboardActions={
 markRead:(conversationId:string,audience:'captain')=>Promise<DashboardResult>;
 broadcast:(allocationId:string,message:string,category:string,requestId:string)=>Promise<DashboardResult>;
 openParty:(allocationId:string,bookingId:string,message:string,category:string,requestId:string)=>Promise<DashboardResult>;
 reply:(conversationId:string,message:string,category:string)=>Promise<DashboardResult>;
 start:(assignmentId:string)=>Promise<DashboardResult>;
 complete:(assignmentId:string,normal:boolean,notes:string,incident:boolean,summary:string)=>Promise<DashboardResult>;
 startLeg?:CaptainTodayActions['startLeg'];endLeg?:CaptainTodayActions['endLeg'];
};
export const defaultCaptainDashboardLoaders:CaptainDashboardLoaders={journeys:loadCaptainMyJourneys,manifest:loadCaptainManifest,conversations:loadCaptainJourneyConversations,messages:loadCaptainJourneyMessages,windows:loadCaptainJourneyMessageWindows,todayDuties:loadCaptainTodayDuties,todayManifest:loadCaptainTodayManifest};
export const defaultCaptainDashboardActions:CaptainDashboardActions={markRead:markJourneyConversationRead,broadcast:captainBroadcastToParties,openParty:captainOpenPartyConversation,reply:captainReplyToParty,start:captainStartJourney,complete:captainCompleteJourney,startLeg:captainStartLeg,endLeg:captainEndLeg};

const emptyRows:RowsLoader=async()=>({data:[],error:null});
const dutyKey=(duty:CaptainTodayDutyRow)=>String(duty.duty_id||duty.confirmed_allocation_id||duty.id||'');
const allocationKey=(row:any)=>String(row.confirmed_allocation_id||row.captain_assignment_id||'');
const windowState=(row:any)=>row?.messaging_window_open?'open' as const:(row?.messaging_opens_at&&new Date(row.messaging_opens_at).getTime()>Date.now()?'scheduled' as const:'closed' as const);
const errorMessage=(value:any)=>value?.message||String(value||'Unable to load captain data.');

function legacyDuty(row:any):CaptainTodayDutyRow{
 const id=allocationKey(row);
 return {...row,id,duty_id:id,confirmed_allocation_id:row.confirmed_allocation_id||id,country_timezone:'UTC',first_scheduled_departure_ts:new Date(),pickup_name:row.pickup_name||'Pickup to be confirmed',leg_1_departure_id:row.captain_assignment_id||id,leg_1_name:row.route_name||'Today’s duty',leg_1_scheduled_departure_ts:row.scheduled_departure_ts,leg_1_scheduled_arrival_ts:row.scheduled_arrival_ts||null,leg_1_started_at:row.actual_departure_ts||null,leg_1_ended_at:row.actual_arrival_ts||null,leg_1_completion_state:row.actual_arrival_ts?'normal':null,leg_2_departure_id:null,leg_2_name:null,leg_2_scheduled_departure_ts:null,leg_2_scheduled_arrival_ts:null,leg_2_started_at:null,leg_2_ended_at:null,leg_2_completion_state:null,vehicle_name:row.vehicle_name||'',operator_name:row.operator_name||''};
}

function useRows(fn:RowsLoader){
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);const request=useRef(0);
 const reload=async(current:()=>boolean=()=>true)=>{const id=++request.current;if(current())setLoading(true);try{const result=await fn(),data=result.data||[],message=result.error?.message||'';if(id===request.current){if(current()){setRows(data);setError(message)}setLoading(false)}return {data,error:result.error};}catch(reason:any){if(id===request.current){if(current()){setRows([]);setError(errorMessage(reason))}setLoading(false)}return {data:[] as any[],error:reason};}};
 useEffect(()=>{void reload();return()=>{request.current++}},[fn]);return {rows,error,loading,reload};
}

function Communications({selected,allocationId,parties,pendingParty,messages,windows,activeConversationId,mode,busy,notice,conversationLoading,conversationError,onChooseParty,onMode,onRetryConversations,onOpenParty,onReply,onBroadcast}:{selected:CaptainTodayDutyRow;allocationId:string;parties:any[];pendingParty:CaptainTodayManifestRow|null;messages:any[];windows:any[];activeConversationId:string;mode:'party'|'all'|'';busy:boolean;notice:string;conversationLoading:boolean;conversationError:string;onChooseParty:(id:string)=>void;onMode:(mode:'party'|'all')=>void;onRetryConversations:()=>void;onOpenParty:(allocationId:string,bookingId:string,message:string,category:string,requestId:string)=>Promise<void>;onReply:(conversationId:string,message:string,category:string)=>Promise<void>;onBroadcast:(allocationId:string,message:string,category:string,requestId:string)=>Promise<void>}){
 const activeParty=parties.find(party=>party.id===activeConversationId),partyMessages=activeParty?messages.filter(message=>message.conversation_id===activeParty.id):[],selectedWindow=windows.find(row=>row.confirmed_allocation_id===allocationId),unread=parties.reduce((total,party)=>total+Number(party.unread_count||0),0);
 const pendingComposer=!conversationLoading&&!conversationError?pendingParty:null;
 return <div className="captain-communications"><div className="captain-communication-actions"><button type="button" className={`btn secondary${mode==='party'?' selected':''}`} onClick={()=>onMode('party')}>Message a party{unread?` · ${unread} unread`:''}</button><button type="button" aria-label="Message all" className={`btn secondary${mode==='all'?' selected':''}`} onClick={()=>onMode('all')}>Message all parties</button></div>
  {mode==='party'?<div className="captain-party-communications">{parties.map((party,index)=><button type="button" aria-label={`Open party ${index+1} conversation`} className={`support-item${activeParty?.id===party.id?' selected':''}`} key={party.id} onClick={()=>onChooseParty(party.id)}><span><b>{party.lead_passenger_name||`Party ${index+1}`}</b><small>Private conversation · {windowState(party)}</small></span>{Number(party.unread_count||0)>0?<small className="unread-badge">Unread {Number(party.unread_count)}</small>:null}</button>)}{conversationLoading?<div className="empty-state" role="status">Loading private party conversations…</div>:null}{conversationError?<div className="action-error" role="alert"><p>{conversationError}</p><button type="button" className="btn secondary" onClick={onRetryConversations}>Retry private conversations</button></div>:null}{activeParty?<JourneyConversation key={`${allocationId}:${activeParty.id}`} threadId={activeParty.id} mode="captain" windowState={windowState(activeParty)} closesAt={activeParty.messaging_closes_at} messages={partyMessages} busy={busy} onSend={(message,category)=>onReply(activeParty.id,message,category)}/>:pendingComposer?<div className="captain-new-party-conversation"><h3>{pendingComposer.lead_passenger_name||'Selected party'}</h3><JourneyConversation key={`${allocationId}:${pendingComposer.booking_id}:new`} mode="captain" newThread windowState={windowState(selectedWindow)} closesAt={selectedWindow?.messaging_closes_at} messages={[]} busy={busy} onSend={(message,category,requestId)=>onOpenParty(allocationId,String(pendingComposer.booking_id||''),message,category,String(requestId||''))}/></div>:!conversationLoading&&!conversationError?<div className="empty-state">{parties.length?'Choose a party to open its private conversation.':'No private party conversations yet.'}</div>:null}</div>:null}
  {mode==='all'?<CaptainBroadcastComposer key={selected.confirmed_allocation_id} allocationId={allocationId} open={windowState(selectedWindow)==='open'} busy={busy} onSend={(message,category,requestId)=>onBroadcast(allocationId,message,category,requestId)}/>:null}{notice?<p className={notice.includes('completed')?'action-success':'action-error'}>{notice}</p>:null}</div>;
}

export function CaptainDashboard({loaders=defaultCaptainDashboardLoaders,actions=defaultCaptainDashboardActions,initialTab,now=new Date()}:{loaders?:CaptainDashboardLoaders;actions?:CaptainDashboardActions;initialTab?:CaptainWorkspaceTab;now?:Date}={}){
 const journeys=useRows(loaders.journeys),manifest=useRows(loaders.manifest),conversations=useRows(loaders.conversations),messages=useRows(loaders.messages),windows=useRows(loaders.windows),todayDuties=useRows(loaders.todayDuties||emptyRows),todayManifest=useRows(loaders.todayManifest||emptyRows),hasProtectedToday=Boolean(loaders.todayDuties&&loaders.todayManifest);
 const [tab,setTab]=useState<CaptainWorkspaceTab>(()=>initialTab||captainWorkspaceTab(typeof window==='undefined'?undefined:new URLSearchParams(window.location.search).get('tab'))),[selectedDutyState,setSelectedDutyState]=useState(''),[selectedConversationId,setSelectedConversationId]=useState(''),[communicationMode,setCommunicationMode]=useState<'party'|'all'|''>(''),[partyIntent,setPartyIntent]=useState<PartyIntent|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
 const contextOperation=useRef(0),refreshRequest=useRef(0),reloadIdentity=useRef<{requestId:string;dutyId:string}|null>(null),mounted=useRef(true);
 const duties=useMemo(()=>hasProtectedToday?todayDuties.rows as CaptainTodayDutyRow[]:journeys.rows.map(legacyDuty),[hasProtectedToday,todayDuties.rows,journeys.rows]),protectedManifest=useMemo(()=>hasProtectedToday?todayManifest.rows as CaptainTodayManifestRow[]:[] as CaptainTodayManifestRow[],[hasProtectedToday,todayManifest.rows]);
 const selectedDuty=useMemo(()=>duties.find(duty=>dutyKey(duty)===selectedDutyState)||selectCurrentDuty(duties,now)||duties[0],[duties,selectedDutyState,now]),selectedDutyId=selectedDuty?dutyKey(selectedDuty):'',selectedDutyRef=useRef(selectedDutyId);selectedDutyRef.current=selectedDutyId;
 const allocationId=String(selectedDuty?.confirmed_allocation_id||selectedDutyId),parties=conversations.rows.filter(row=>row.confirmed_allocation_id===allocationId),activeParty=parties.find(row=>row.id===selectedConversationId),pendingParty=partyIntent?.dutyId===selectedDutyId&&partyIntent.allocationId===allocationId?protectedManifest.find(row=>String(row.booking_id||'')===partyIntent.bookingId)||null:null;
 useEffect(()=>{mounted.current=true;const pop=()=>{setTab(captainWorkspaceTab(new URLSearchParams(window.location.search).get('tab')));invalidateContext()};window.addEventListener('popstate',pop);return()=>{mounted.current=false;contextOperation.current++;refreshRequest.current++;reloadIdentity.current=null;window.removeEventListener('popstate',pop)}},[]);
 useEffect(()=>{let cancelled=false;if(!activeParty||!Number(activeParty.unread_count||0))return;void (async()=>{try{const result=await actions.markRead(activeParty.id,'captain');if(!cancelled&&!result.error){const generation=++refreshRequest.current,current=()=>!cancelled&&generation===refreshRequest.current;await Promise.all([conversations.reload(current),todayManifest.reload(current)])}}catch{}})();return()=>{cancelled=true}},[actions,activeParty?.id,activeParty?.unread_count]);
 useEffect(()=>{if(!partyIntent)return;if(tab!=='today'||selectedDutyId!==partyIntent.dutyId||allocationId!==partyIntent.allocationId){setPartyIntent(null);return}const chosen=conversations.rows.find(row=>String(row.confirmed_allocation_id||'')===partyIntent.allocationId&&String(row.booking_id||'')===partyIntent.bookingId);if(chosen){setSelectedConversationId(chosen.id);setPartyIntent(null)}},[partyIntent,tab,selectedDutyId,allocationId,conversations.rows]);
 const invalidateContext=()=>{contextOperation.current++;setBusy('');setNotice('');setSelectedConversationId('');setCommunicationMode('');setPartyIntent(null)},selectDuty=(id:string)=>{invalidateContext();setSelectedDutyState(id)},navigate=(next:CaptainWorkspaceTab)=>{const canonical=window.location.pathname==='/captain'&&window.location.search===`?tab=${next}`;if(next===tab&&canonical)return;window.history.pushState({},'',`/captain?tab=${next}`);if(next!==tab){setTab(next);invalidateContext()}};
 const refresh=async(allowed:()=>boolean=()=>true)=>{const generation=++refreshRequest.current,current=()=>generation===refreshRequest.current&&allowed(),results=await Promise.all([journeys.reload(current),manifest.reload(current),conversations.reload(current),messages.reload(current),windows.reload(current),todayDuties.reload(current),todayManifest.reload(current)]);return {generation,results:current()?results:null}};
 const reloadToday=async({dutyId,requestId,signal}:CaptainTodayReloadRequest):Promise<CaptainTodayReloadResult>=>{const allowed=()=>mounted.current&&!signal.aborted&&reloadIdentity.current?.requestId===requestId&&reloadIdentity.current.dutyId===dutyId&&selectedDutyRef.current===dutyId;if(!mounted.current||signal.aborted||selectedDutyRef.current!==dutyId)throw new DOMException('Today refresh was cancelled.','AbortError');reloadIdentity.current={requestId,dutyId};const batch=await refresh(allowed);if(!allowed()||refreshRequest.current!==batch.generation||!batch.results)throw new DOMException('Today refresh was cancelled.','AbortError');const dutyResult=hasProtectedToday?batch.results[5]:batch.results[0],manifestResult=hasProtectedToday?batch.results[6]:batch.results[1];if(dutyResult.error)throw dutyResult.error;if(manifestResult.error)throw manifestResult.error;return {duties:hasProtectedToday?dutyResult.data as CaptainTodayDutyRow[]:dutyResult.data.map(legacyDuty),manifest:hasProtectedToday?manifestResult.data as CaptainTodayManifestRow[]:[]}};
 const runMessage=async(label:string,identity:string,action:()=>Promise<DashboardResult>)=>{const id=++contextOperation.current,current=()=>mounted.current&&id===contextOperation.current;setBusy(label);setNotice('');let result:DashboardResult;try{result=await action()}catch(reason){if(current()){setBusy('');setNotice(errorMessage(reason))}throw reason}if(result.error){if(current()){setBusy('');setNotice(errorMessage(result.error))}throw result.error}await refresh();if(current()&&selectedDutyRef.current===identity){setNotice(`${label} completed`);setBusy('')}};
 const openParty=(identity:string,bookingId:string,message:string,category:string,requestId:string)=>runMessage('Private conversation',selectedDutyId,()=>actions.openParty(identity,bookingId,message,category,requestId)),reply=(conversationId:string,message:string,category:string)=>runMessage('Party reply',selectedDutyId,()=>actions.reply(conversationId,message,category)),broadcast=(identity:string,message:string,category:string,requestId:string)=>runMessage('Passenger update',selectedDutyId,()=>actions.broadcast(identity,message,category,requestId));
 const legActions:CaptainTodayActions={startLeg:actions.startLeg||actions.start,endLeg:actions.endLeg||((id,state,notes,summary)=>actions.complete(id,state==='normal',notes,state==='incident',summary))};
 const openManifestParty=(party:CaptainTodayManifestRow)=>{const intent={dutyId:selectedDutyId,allocationId,bookingId:String(party.booking_id||'')},chosen=parties.find(row=>String(row.confirmed_allocation_id||'')===allocationId&&String(row.booking_id||'')===intent.bookingId);invalidateContext();setCommunicationMode('party');if(chosen)setSelectedConversationId(chosen.id);else setPartyIntent(intent);queueMicrotask(()=>document.getElementById('communications')?.scrollIntoView?.({block:'start'}))};
 const retryConversations=()=>{const generation=++refreshRequest.current,current=()=>generation===refreshRequest.current;void Promise.all([conversations.reload(current),messages.reload(current),windows.reload(current),todayManifest.reload(current)])};
 const retryGeneral=()=>{const id=++refreshRequest.current,current=()=>id===refreshRequest.current;void Promise.all([journeys.reload(current),...(hasProtectedToday?[todayDuties.reload(current)]:[])])};
 const error=journeys.error||manifest.error||conversations.error||messages.error||windows.error||todayDuties.error||todayManifest.error,loadingToday=hasProtectedToday?(todayDuties.loading||todayManifest.loading):journeys.loading,todayIds=useMemo(()=>new Set(duties.map(duty=>String(duty.confirmed_allocation_id||dutyKey(duty)))),[duties]),generalLoading=journeys.loading||(hasProtectedToday&&todayDuties.loading),generalError=journeys.error||(hasProtectedToday?todayDuties.error:'');
  return <div className="captain-workspace"><CaptainWorkspaceTabs active={tab} onNavigate={navigate}/>{tab==='general'?<CaptainGeneral journeys={journeys.rows} todayAllocationIds={todayIds} now={now} onOpenToday={()=>navigate('today')} onRetry={retryGeneral} loading={generalLoading} error={generalError}/>:loadingToday&&!duties.length?<div className="empty-state" role="status">Loading today’s duties…</div>:<><CaptainToday duties={duties} manifest={protectedManifest} now={now} selectedDutyId={selectedDutyId} onSelectedDutyIdChange={selectDuty} onMessageParty={openManifestParty} onReload={reloadToday} actions={legActions} communications={selectedDuty?<Communications selected={selectedDuty} allocationId={allocationId} parties={parties} pendingParty={pendingParty} messages={messages.rows} windows={windows.rows} activeConversationId={selectedConversationId} mode={communicationMode} busy={Boolean(busy)} notice={notice} conversationLoading={conversations.loading} conversationError={conversations.error} onChooseParty={id=>{invalidateContext();setCommunicationMode('party');setSelectedConversationId(id)}} onMode={mode=>{if(mode!==communicationMode){invalidateContext();setCommunicationMode(mode);if(mode==='party')setSelectedConversationId(parties[0]?.id||'')}}} onRetryConversations={retryConversations} onOpenParty={openParty} onReply={reply} onBroadcast={broadcast}/>:null}/>{error?<p className="action-error" role="alert">{error}</p>:null}</>}</div>;
}
