'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {getSupabaseBrowserClient} from '@/lib/supabase';
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((c||0)/100);
export default function Checkout(){
 const sp=useSearchParams(),qid=sp.get('q'),s=getSupabaseBrowserClient();
 const [q,setQ]=useState<any>(null),[session,setSession]=useState<any>(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[last,setLast]=useState(''),[pass,setPass]=useState<any[]>([]),[msg,setMsg]=useState(''),[done,setDone]=useState<any>(null),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{(async()=>{if(!s||!qid)return;const [{data,error},{data:ss}]=await Promise.all([s.rpc('v2_public_get_quote_intent',{p_quote_id:qid}),s.auth.getSession()]);if(error){setMsg(error.message);return}const row=data?.[0];setQ(row||null);setSession(ss.session);if(ss.session?.user?.email)setEmail(ss.session.user.email);setPass(Array.from({length:row?.party_size||0},()=>({first_name:'',last_name:'',age_group:'adult'})))})()},[s,qid]);
 const expired=useMemo(()=>q?new Date(q.expires_at).getTime()<=now:false,[q,now]);
 const remaining=useMemo(()=>q?Math.max(0,Math.ceil((new Date(q.expires_at).getTime()-now)/1000)):0,[q,now]);
 const passengerReady=pass.length>0&&pass.every(p=>String(p.first_name||'').trim()&&String(p.last_name||'').trim());
 const formReady=!!name.trim()&&!!last.trim()&&!!email.trim()&&passengerReady&&!expired;
 async function signIn(){if(!s||!email||expired)return;setBusy(true);setMsg('Sending secure sign-in link…');const {error}=await s.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.href}});setBusy(false);setMsg(error?.message||'Check your email for the secure sign-in link, then return here. Your held price remains valid until the time shown.')}
 async function reserve(){if(!s||!qid||!formReady)return;setBusy(true);setMsg('Reserving your seats…');const {data,error}=await s.rpc('v2_customer_commit_quote',{p_quote_id:qid,p_customer_name:name.trim(),p_customer_email:email.trim(),p_lead_last_name:last.trim(),p_passengers:pass});setBusy(false);if(error)setMsg(error.message);else{setDone(data?.[0]);setMsg('')}}
 async function pay(){if(!s||!done?.order_id)return;setBusy(true);setMsg('Opening secure payment…');const {data:{session}}=await s.auth.getSession();const r=await fetch('/api/stripe/create-checkout-session',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({orderId:done.order_id})});const j=await r.json();if(!r.ok){setBusy(false);setMsg(j.error||'Unable to start payment');return}if(j.url)window.location.assign(j.url)}
 if(!qid)return <div className="ps-checkout"><p>Missing quote reference.</p><Link href="/book">Return to journeys</Link></div>;
 if(!q&&!msg)return <div className="ps-checkout"><p>Loading your journey…</p></div>;
 if(!q)return <div className="ps-checkout"><div className="ps-alert">{msg||'This quote is no longer available.'}</div><Link className="ps-primary" href="/book">Choose another journey</Link></div>;
 const snap=q.quote_snapshot||{};
 if(done)return <main className="ps-checkout"><div className="ps-confirm"><div className="ps-tick">✓</div><h1>Your seats are reserved</h1><p>{done.route_name}</p><strong>{money(done.total_cents)}</strong><p className="muted">Complete secure card payment to confirm your booking. Your whole party remains together.</p><button className="ps-primary wide" disabled={busy} onClick={pay}>{busy?'Opening payment…':`Pay ${money(done.total_cents)} securely`}</button>{msg&&<div className="ps-alert">{msg}</div>}<Link href="/book">Choose another journey</Link></div></main>;
 return <main className="ps-checkout"><header><Link href="/book">← Back to journeys</Link><b>Pace Shuttles</b></header><div className="ps-checkout-grid"><section><p className="eyebrow">Complete your booking</p><h1>{snap.pickup_name} → {snap.destination_name}</h1><p>{new Date(snap.scheduled_departure_ts).toLocaleString([],{weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})} · {q.party_size} seat{q.party_size===1?'':'s'}</p>{expired&&<div className="ps-alert">This held price has expired. Return to the journey list to obtain a fresh live price.</div>}<div className="ps-form"><label>Lead passenger first name<input autoComplete="given-name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Lead passenger surname<input autoComplete="family-name" value={last} onChange={e=>setLast(e.target.value)}/></label><label>Email<input autoComplete="email" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><h3>Passengers</h3>{pass.map((p,i)=><div className="ps-passenger" key={i}><input placeholder={`Passenger ${i+1} first name`} value={p.first_name} onChange={e=>setPass(a=>a.map((x,j)=>j===i?{...x,first_name:e.target.value}:x))}/><input placeholder="Last name" value={p.last_name} onChange={e=>setPass(a=>a.map((x,j)=>j===i?{...x,last_name:e.target.value}:x))}/><select aria-label={`Passenger ${i+1} age group`} value={p.age_group} onChange={e=>setPass(a=>a.map((x,j)=>j===i?{...x,age_group:e.target.value}:x))}><option value="adult">Adult</option><option value="child">Child</option><option value="infant">Infant</option></select></div>)}</div>{!session?<button className="ps-primary wide" disabled={!email||busy||expired} onClick={signIn}>{busy?'Sending…':'Sign in securely to continue'}</button>:<button className="ps-primary wide" disabled={!formReady||busy} onClick={reserve}>{busy?'Reserving…':'Reserve seats'}</button>}{msg&&<div className="ps-alert">{msg}</div>}</section><aside className="ps-summary"><h2>Journey summary</h2><div><span>Seat price</span><b>{money(q.unit_price_cents)}</b></div><div><span>Seats</span><b>{q.party_size}</b></div><div className="total"><span>Total incl. tax & fees</span><b>{money(q.total_price_cents)}</b></div><small>{expired?'Price hold expired.':`Live price held for ${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}.`}</small><p className="muted">Your whole party is kept together; Pace Shuttles will not split the booking across vehicles.</p></aside></div></main>;
}
