'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {getSupabaseBrowserClient} from '@/lib/supabase';
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((c||0)/100);
const img=(x?:string|null)=>x||'/pace-hero.jpg';
export default function CustomerBooking(){
 const s=getSupabaseBrowserClient(); const [countries,setCountries]=useState<any[]>([]),[deps,setDeps]=useState<any[]>([]),[country,setCountry]=useState(''),[dest,setDest]=useState(''),[pickup,setPickup]=useState(''),[day,setDay]=useState(''),[party,setParty]=useState(2),[quotes,setQuotes]=useState<Record<string,any>>({}),[loading,setLoading]=useState(true),[msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{if(!s)return; const [c,d]=await Promise.all([s.from('v2_public_countries').select('*').order('display_order'),s.from('v2_public_departures').select('*').order('scheduled_departure_ts')]);setCountries(c.data||[]);setDeps(d.data||[]);setLoading(false)})()},[s]);
 const filtered=useMemo(()=>deps.filter(x=>(!country||x.country_id===country)&&(!dest||x.destination_id===dest)&&(!pickup||x.pickup_id===pickup)&&(!day||x.local_departure_date===day)),[deps,country,dest,pickup,day]);
 const dests=useMemo(()=>Array.from(new Map(deps.filter(x=>!country||x.country_id===country).map(x=>[x.destination_id,{id:x.destination_id,name:x.destination_name,picture_url:x.destination_picture_url,description:x.destination_description}])).values()),[deps,country]);
 const pickups=useMemo(()=>Array.from(new Map(deps.filter(x=>(!country||x.country_id===country)&&(!dest||x.destination_id===dest)).map(x=>[x.pickup_id,{id:x.pickup_id,name:x.pickup_name,picture_url:x.pickup_picture_url}])).values()),[deps,country,dest]);
 async function quote(id:string){if(!s)return;setMsg('');const {data,error}=await s.rpc('v2_public_quote',{p_departure_id:id,p_party_size:party});if(error)setMsg(error.message);else setQuotes(q=>({...q,[id]:data?.[0]}))}
 async function choose(id:string){if(!s)return;setMsg('');const {data,error}=await s.rpc('v2_public_create_quote_intent',{p_departure_id:id,p_party_size:party});if(error){setMsg(error.message);return} window.location.href='/checkout?q='+encodeURIComponent(data)}
 return <main className="ps-public"><header className="ps-public-header"><Link href="/" className="ps-wordmark">Pace Shuttles</Link><nav><Link href="/">Home</Link><Link href="/book" className="active">Book</Link><Link href="/customer">My journeys</Link></nav></header>
 <section className="ps-intro"><div><p className="eyebrow">Luxury Transfers, Reimagined.</p><h1>With Pace Shuttles, the journey <em>is</em> the destination.</h1><p>Discover semi-private, shared journeys between exclusive islands and shores — with one intelligent platform handling availability, pricing and your booking.</p><a className="ps-primary" href="#journeys">Find a journey</a></div><div className="ps-hero"><Image src="/pace-hero.jpg" alt="Pace Shuttles luxury transfer" fill priority className="cover"/></div></section>
 {!country&&<section className="ps-section"><h2>Where would you like to travel?</h2><p className="muted">Select a location to begin your journey.</p><div className="ps-tile-grid">{countries.map(c=><button className="ps-tile" key={c.id} onClick={()=>{setCountry(c.id);setDest('');setPickup('')}}><div className="ps-tile-img"><Image src={img(c.picture_url||c.hero_image_url)} alt={c.name} fill className="cover" unoptimized/></div><div className="ps-tile-copy"><b>{c.name}</b><span>{c.description||c.blurb||'Explore available journeys'}</span></div></button>)}</div></section>}
 {country&&<section className="ps-section" id="journeys"><div className="ps-planner-head"><div><button className="ps-back" onClick={()=>{setCountry('');setDest('');setPickup('');setDay('')}}>← Change location</button><h2>Plan your journey</h2></div><label>Seats<select value={party} onChange={e=>{setParty(+e.target.value);setQuotes({})}}>{Array.from({length:12},(_,i)=>i+1).map(n=><option key={n}>{n}</option>)}</select></label></div>
 <div className="ps-filters"><label>Destination<select value={dest} onChange={e=>{setDest(e.target.value);setPickup('')}}><option value="">All destinations</option>{dests.map((d:any)=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>Pick-up<select value={pickup} onChange={e=>setPickup(e.target.value)}><option value="">All pick-up points</option>{pickups.map((p:any)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Date<input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label></div>
 {msg&&<div className="ps-alert">{msg}</div>} {loading?<div className="ps-empty">Loading journeys…</div>:filtered.length===0?<div className="ps-empty">No journeys match those choices yet.</div>:<div className="ps-results">{filtered.map(x=>{const q=quotes[x.departure_id];return <article className="ps-journey" key={x.departure_id}><div className="ps-route-images"><div><Image src={img(x.pickup_picture_url)} alt={x.pickup_name} fill className="cover" unoptimized/></div><div><Image src={img(x.destination_picture_url)} alt={x.destination_name} fill className="cover" unoptimized/></div></div><div className="ps-journey-main"><div><h3>{x.pickup_name} → {x.destination_name}</h3><p>{new Date(x.scheduled_departure_ts).toLocaleString([],{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}{x.approx_duration_mins?` · ${x.approx_duration_mins} mins`:''}</p><small>{(x.vehicle_types||[]).map((v:any)=>v.name).join(' · ')}</small></div><div className="ps-price">{q?.result_status==='offer'?<><span>Per seat incl. tax & fees</span><strong>{money(q.all_in_unit_price_cents)}</strong><small>{party} seat{party===1?'':'s'} · {money(q.all_in_total_cents)} total</small></>:<><span>Live pricing</span><strong>—</strong></>}</div><div className="ps-actions">{q?.result_status==='offer'?<button className="ps-primary" onClick={()=>choose(x.departure_id)}>Continue</button>:<button className="ps-primary" onClick={()=>quote(x.departure_id)}>Check price</button>}</div></div></article>})}</div>}</section>}
 <section className="ps-footer-cta"><Image src="/partners-cta.jpg" alt="Partner with Pace Shuttles" width={2400} height={600}/></section><footer className="ps-footer">Pace Shuttles · Shared premium journeys, intelligently connected.</footer></main>
}
