'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {getSupabaseBrowserClient} from '@/lib/supabase';
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((c||0)/100);
const fallback='/pace-hero.jpg';
function Photo({src,alt,className=''}:{src?:string|null,alt:string,className?:string}){
 return <img src={src||fallback} alt={alt} className={className} onError={e=>{const el=e.currentTarget;if(!el.src.endsWith(fallback))el.src=fallback}}/>;
}
export default function CustomerBooking(){
 const s=getSupabaseBrowserClient();
 const [countries,setCountries]=useState<any[]>([]),[catalogDests,setCatalogDests]=useState<any[]>([]),[catalogPickups,setCatalogPickups]=useState<any[]>([]),[deps,setDeps]=useState<any[]>([]),[country,setCountry]=useState(''),[dest,setDest]=useState(''),[pickup,setPickup]=useState(''),[day,setDay]=useState(''),[party,setParty]=useState(2),[quotes,setQuotes]=useState<Record<string,any>>({}),[loading,setLoading]=useState(true),[msg,setMsg]=useState(''),[browseTab,setBrowseTab]=useState<'destination'|'pickup'|'date'|'type'>('destination');
 useEffect(()=>{(async()=>{if(!s)return; const [c,cd,cp,d]=await Promise.all([s.from('v2_public_countries').select('*').order('display_order'),s.from('v2_public_destinations').select('*').order('sort_order').order('name'),s.from('v2_public_pickups').select('*').order('sort_order').order('name'),s.from('v2_public_departures').select('*').order('scheduled_departure_ts')]);setCountries(c.data||[]);setCatalogDests(cd.data||[]);setCatalogPickups(cp.data||[]);setDeps(d.data||[]);setLoading(false)})()},[s]);
 const filtered=useMemo(()=>deps.filter(x=>(!country||x.country_id===country)&&(!dest||x.destination_id===dest)&&(!pickup||x.pickup_id===pickup)&&(!day||x.local_departure_date===day)),[deps,country,dest,pickup,day]);
 const dests=useMemo(()=>catalogDests.filter(x=>!country||x.country_id===country),[catalogDests,country]);
 const pickups=useMemo(()=>{const availableIds=new Set(deps.filter(x=>(!country||x.country_id===country)&&(!dest||x.destination_id===dest)).map(x=>x.pickup_id));const all=catalogPickups.filter(x=>!country||x.country_id===country);return [...all].sort((a,b)=>Number(availableIds.has(b.id))-Number(availableIds.has(a.id))||(a.sort_order||0)-(b.sort_order||0)||String(a.name).localeCompare(String(b.name)))},[catalogPickups,deps,country,dest]);
 const dates=useMemo(()=>Array.from(new Set(deps.filter(x=>(!country||x.country_id===country)&&(!dest||x.destination_id===dest)).map(x=>x.local_departure_date))).filter(Boolean).sort(),[deps,country,dest]);
 const types=useMemo(()=>{const m=new Map<string,any>();deps.filter(x=>(!country||x.country_id===country)&&(!dest||x.destination_id===dest)).forEach(x=>(x.vehicle_types||[]).forEach((v:any)=>m.set(v.id||v.name,v)));return Array.from(m.values())},[deps,country,dest]);
 async function quote(id:string){if(!s)return;setMsg('');const {data,error}=await s.rpc('v2_public_quote',{p_departure_id:id,p_party_size:party});if(error)setMsg(error.message);else setQuotes(q=>({...q,[id]:data?.[0]}))}
 async function choose(id:string){if(!s)return;setMsg('');const {data,error}=await s.rpc('v2_public_create_quote_intent',{p_departure_id:id,p_party_size:party});if(error){setMsg(error.message);return} window.location.href='/checkout?q='+encodeURIComponent(data)}
 function resetCountry(){setCountry('');setDest('');setPickup('');setDay('');setQuotes({});setBrowseTab('destination')}
 function chooseDestination(id:string){setDest(id);setPickup('');setDay('');setQuotes({})}
 return <main className="ps-public"><header className="ps-public-header"><Link href="/" className="ps-wordmark"><Image src="/logo.jpeg" alt="Pace Shuttles" width={148} height={44}/></Link><nav><Link href="/">Home</Link><Link href="/book" className="active">Book</Link><Link href="/customer">My journeys</Link></nav></header>
 <section className="ps-intro"><div><p className="eyebrow">Luxury Transfers, Reimagined.</p><h1>With Pace Shuttles, the journey <em>is</em> the destination.</h1><p>Discover semi-private, shared journeys between exclusive islands and shores — with one intelligent platform handling availability, pricing and your booking.</p><a className="ps-primary" href="#journeys">Find a journey</a></div><div className="ps-hero"><Image src="/pace-hero.jpg" alt="Pace Shuttles luxury transfer" fill priority className="cover"/></div></section>
 {!country&&<section className="ps-section ps-country-stage" id="journeys"><h2>Where would you like to travel?</h2><p className="muted">Select a location to begin your journey.</p><div className="ps-country-grid">{countries.map(c=><button className="ps-country-card" key={c.id} onClick={()=>{setCountry(c.id);setDest('');setPickup('');setBrowseTab('destination')}}><Photo src={c.picture_url||c.hero_image_url} alt={c.name}/><div className="ps-country-overlay"><b>{c.name}</b><span>{c.description||c.blurb||'Explore available journeys'}</span></div></button>)}</div></section>}
 {country&&!dest&&<section className="ps-section ps-discovery" id="journeys"><button className="ps-back-chip" onClick={resetCountry}>← change country</button><div className="ps-discovery-panel"><div className="ps-discovery-tabs"><button className={browseTab==='date'?'active':''} onClick={()=>setBrowseTab('date')}>Date</button><button className={browseTab==='destination'?'active':''} onClick={()=>setBrowseTab('destination')}>Destination</button><button className={browseTab==='pickup'?'active':''} onClick={()=>setBrowseTab('pickup')}>Pickup</button><button className={browseTab==='type'?'active':''} onClick={()=>setBrowseTab('type')}>Type</button></div>
 {browseTab==='destination'&&<><p className="ps-discovery-label">Choose a destination</p>{dests.length?<div className="ps-destination-grid">{dests.map((d:any)=>{const hasJourney=deps.some(x=>x.country_id===country&&x.destination_id===d.id);return <button key={d.id} className={`ps-destination-card${hasJourney?'':' ps-coming-soon'}`} onClick={()=>chooseDestination(d.id)}><Photo src={d.picture_url} alt={d.name}/><div><b>{d.name}</b>{!hasJourney&&<span className="ps-card-badge">Journeys coming soon</span>}<p>{d.description||'Discover this destination with Pace Shuttles.'}</p></div></button>})}</div>:<div className="ps-catalog-empty"><b>Destinations coming soon</b><p>We already serve this location in the Pace Shuttles catalogue. New bookable journeys will appear here as routes are activated.</p></div>}</>}
 {browseTab==='pickup'&&<><p className="ps-discovery-label">Choose your pick-up point</p>{pickups.length?<div className="ps-destination-grid">{pickups.map((p:any)=>{const hasJourney=deps.some(x=>x.country_id===country&&x.pickup_id===p.id&&(!dest||x.destination_id===dest));return <button key={p.id} className={`ps-destination-card${hasJourney?'':' ps-coming-soon'}`} onClick={()=>{setPickup(p.id);setBrowseTab('destination')}}><Photo src={p.picture_url} alt={p.name}/><div><b>{p.name}</b>{!hasJourney&&<span className="ps-card-badge">No live journey yet</span>}<p>{p.description||'Start your Pace Shuttles journey here.'}</p></div></button>})}</div>:<div className="ps-catalog-empty"><b>Pick-up points coming soon</b><p>Pick-up locations will appear here as services are added.</p></div>}</>}
 {browseTab==='date'&&<><p className="ps-discovery-label">Choose a date</p><div className="ps-date-grid">{dates.map((d:any)=><button key={d} onClick={()=>{setDay(d);setBrowseTab('destination')}}>{new Date(d+'T12:00:00').toLocaleDateString([],{weekday:'short',day:'numeric',month:'short'})}</button>)}</div></>}
 {browseTab==='type'&&<><p className="ps-discovery-label">Choose how you want to travel</p><div className="ps-type-grid">{types.map((t:any)=><div key={t.id||t.name} className="ps-type-card"><Photo src={t.picture_url} alt={t.name}/><b>{t.name}</b></div>)}</div></>}
 </div></section>}
 {country&&dest&&<section className="ps-section" id="journeys"><div className="ps-planner-head"><div><button className="ps-back" onClick={()=>{setDest('');setPickup('');setDay('');setQuotes({})}}>← Back to destinations</button><h2>Plan your journey</h2></div><label>Seats<select value={party} onChange={e=>{setParty(+e.target.value);setQuotes({})}}>{Array.from({length:12},(_,i)=>i+1).map(n=><option key={n}>{n}</option>)}</select></label></div>
 <div className="ps-filters"><label>Destination<select value={dest} onChange={e=>{setDest(e.target.value);setPickup('')}}>{dests.map((d:any)=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>Pick-up<select value={pickup} onChange={e=>setPickup(e.target.value)}><option value="">All pick-up points</option>{pickups.map((p:any)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Date<input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label></div>
 {msg&&<div className="ps-alert">{msg}</div>} {loading?<div className="ps-empty">Loading journeys…</div>:filtered.length===0?<div className="ps-empty">No journeys match those choices yet.</div>:<div className="ps-results">{filtered.map(x=>{const q=quotes[x.departure_id];return <article className="ps-journey" key={x.departure_id}><div className="ps-route-images"><div><Photo src={x.pickup_picture_url} alt={x.pickup_name}/></div><div><Photo src={x.destination_picture_url} alt={x.destination_name}/></div></div><div className="ps-journey-main"><div><h3>{x.pickup_name} → {x.destination_name}</h3><p>{new Date(x.scheduled_departure_ts).toLocaleString([],{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}{x.approx_duration_mins?` · ${x.approx_duration_mins} mins`:''}</p><small>{(x.vehicle_types||[]).map((v:any)=>v.name).join(' · ')}</small></div><div className="ps-price">{q?.result_status==='offer'?<><span>Per seat incl. tax & fees</span><strong>{money(q.all_in_unit_price_cents)}</strong><small>{party} seat{party===1?'':'s'} · {money(q.all_in_total_cents)} total</small></>:<><span>Live pricing</span><strong>—</strong></>}</div><div className="ps-actions">{q?.result_status==='offer'?<button className="ps-primary" onClick={()=>choose(x.departure_id)}>Continue</button>:<button className="ps-primary" onClick={()=>quote(x.departure_id)}>Check price</button>}</div></div></article>})}</div>}</section>}
 <section className="ps-footer-cta"><Image src="/partners-cta.jpg" alt="Partner with Pace Shuttles" width={2400} height={600}/></section><footer className="ps-footer">Pace Shuttles · Shared premium journeys, intelligently connected.</footer></main>
}
