'use client';
import Link from 'next/link'; import {useEffect,useState} from 'react'; import {useSearchParams} from 'next/navigation'; import {getSupabaseBrowserClient} from '@/lib/supabase';
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((c||0)/100);
export default function Checkout(){const sp=useSearchParams(),qid=sp.get('q'),s=getSupabaseBrowserClient();const [q,setQ]=useState<any>(null),[session,setSession]=useState<any>(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[last,setLast]=useState(''),[pass,setPass]=useState<any[]>([]),[msg,setMsg]=useState(''),[done,setDone]=useState<any>(null);
 useEffect(()=>{(async()=>{if(!s||!qid)return;const [{data},{data:ss}]=await Promise.all([s.rpc('v2_public_get_quote_intent',{p_quote_id:qid}),s.auth.getSession()]);const row=data?.[0];setQ(row);setSession(ss.session);if(ss.session?.user?.email)setEmail(ss.session.user.email);setPass(Array.from({length:row?.party_size||0},()=>({first_name:'',last_name:'',age_group:'adult'})))})()},[s,qid]);
 async function signIn(){if(!s||!email)return;setMsg('Sending secure sign-in link…');const {error}=await s.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.href}});setMsg(error?.message||'Check your email for the secure sign-in link, then return here.')}
 async function reserve(){if(!s||!qid)return;setMsg('Reserving your seats…');const {data,error}=await s.rpc('v2_customer_commit_quote',{p_quote_id:qid,p_customer_name:name,p_customer_email:email,p_lead_last_name:last,p_passengers:pass});if(error)setMsg(error.message);else{setDone(data?.[0]);setMsg('')}}
 if(!qid)return <div className="ps-checkout"><p>Missing quote reference.</p><Link href="/">Return to journeys</Link></div>; if(!q)return <div className="ps-checkout"><p>Loading your journey…</p></div>;const snap=q.quote_snapshot||{};
 if(done)return <main className="ps-checkout"><div className="ps-confirm"><div className="ps-tick">✓</div><h1>Your seats are reserved</h1><p>{done.route_name}</p><strong>{money(done.total_cents)}</strong><p className="muted">Payment is still pending. Phase 2 will connect this reservation to Stripe checkout.</p><Link className="ps-primary" href="/customer">View my journeys</Link></div></main>;
 return <main className="ps-checkout"><header><Link href="/">← Back to journeys</Link><b>Pace Shuttles</b></header><div className="ps-checkout-grid"><section><p className="eyebrow">Complete your booking</p><h1>{snap.pickup_name} → {snap.destination_name}</h1><p>{new Date(snap.scheduled_departure_ts).toLocaleString()} · {q.party_size} seat{q.party_size===1?'':'s'}</p><div className="ps-form"><label>Lead passenger name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Lead passenger surname<input value={last} onChange={e=>setLast(e.target.value)}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><h3>Passenger names</h3>{pass.map((p,i)=><div className="ps-passenger" key={i}><input placeholder={`Passenger ${i+1} first name`} value={p.first_name} onChange={e=>setPass(a=>a.map((x,j)=>j===i?{...x,first_name:e.target.value}:x))}/><input placeholder="Last name" value={p.last_name} onChange={e=>setPass(a=>a.map((x,j)=>j===i?{...x,last_name:e.target.value}:x))}/></div>)}</div>{!session?<button className="ps-primary wide" onClick={signIn}>Sign in securely to continue</button>:<button className="ps-primary wide" disabled={!name||!email} onClick={reserve}>Reserve seats</button>}{msg&&<div className="ps-alert">{msg}</div>}</section><aside className="ps-summary"><h2>Journey summary</h2><div><span>Seat price</span><b>{money(q.unit_price_cents)}</b></div><div><span>Seats</span><b>{q.party_size}</b></div><div className="total"><span>Total incl. tax & fees</span><b>{money(q.total_price_cents)}</b></div><small>Live price held until {new Date(q.expires_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}.</small></aside></div></main>}
