'use client';
import Link from 'next/link';
import { journeys, operators, kpis, countries } from '@/lib/mock';
import { KpiCard, Progress, RowLink, Section, Status } from './ui';

export function JourneyDetail({id}:{id:string}){
 const j=journeys.find(x=>x.id===id)||journeys[0];
 return <>
  <section className="card hero-strip">
    <div className="hero-cell"><small>Route</small><strong>{j.route}</strong><small>{j.country}</small></div>
    <div className="hero-cell"><small>Journey ID</small><strong>{j.id}</strong></div>
    <div className="hero-cell"><small>Vehicle</small><strong>{j.vehicle}</strong><small>{j.type}</small></div>
    <div className="hero-cell"><small>Captain</small><strong>{j.captain}</strong></div>
    <div className="hero-cell"><small>Seats</small><strong>{j.seats}</strong></div>
    <div className="hero-cell"><small>Revenue</small><strong>{j.revenue}</strong></div>
    <div className="hero-cell"><small>Commission</small><strong>{j.commission}</strong></div>
    <div className="hero-cell"><small>Status</small><strong><Status value={j.status}/></strong></div>
  </section>
  <div className="tabs">{['Overview','Bookings & Passengers','Allocation & Competition','Operator & Vehicle','Operations','Financials','Timeline & History','Messages & Notes','Support'].map((x,i)=><a key={x} className={i===0?'active':''}>{x}</a>)}</div>
  <div className="grid-3">
    <Section title="Journey Timeline"><div className="notice-list"><div className="notice"><span>Journey created</span><b>29 May, 14:12</b></div><div className="notice"><span>Under consideration started (T-72)</span><b>28 May, 08:30</b></div><div className="notice"><span>Confirmed at T-24</span><b>30 May, 08:30</b></div><div className="notice warn"><span>Departure</span><b>In 19h 28m</b></div></div></Section>
    <Section title="Allocation Summary"><div className="metric-pair"><div className="mini-metric"><small>Allocated Operator</small><strong>{j.operator}</strong><small>Quality 82.4 / 100</small></div><div className="mini-metric"><small>Allocation Outcome</small><strong>{j.revenue}</strong><small>{j.commission} commission</small></div></div><table className="table"><thead><tr><th>Rank</th><th>Operator</th><th>Price/Seat</th><th>Score</th><th>Result</th></tr></thead><tbody><tr><td>1</td><td>Barefoot</td><td>$200</td><td>82.4</td><td><Status value="CONFIRMED"/></td></tr><tr><td>2</td><td>Island Ride</td><td>$210</td><td>76.1</td><td>Lost</td></tr><tr><td>3</td><td>Coastal Rides</td><td>$230</td><td>71.3</td><td>Lost</td></tr></tbody></table></Section>
    <Section title="Journey at a Glance"><RowLink href="#">Pickup: Jolly Harbour Marina</RowLink><RowLink href="#">Drop off: Nobu, Barbuda</RowLink><RowLink href="#">Max passengers: 8</RowLink><RowLink href="#">Min seats / revenue: 4 / $800</RowLink><RowLink href="#">Booking cut-off: 2h before</RowLink></Section>
  </div>
  <div className="grid-3" style={{marginTop:12}}>
    <Section title="Bookings & Passengers"><table className="table"><thead><tr><th>Booking</th><th>Lead</th><th>Party</th><th>Price</th></tr></thead><tbody><tr><td>BKG-14782</td><td>Emma Johnson</td><td>4</td><td>$800</td></tr><tr><td>BKG-14783</td><td>David Williams</td><td>2</td><td>$400</td></tr></tbody></table></Section>
    <Section title="Financial Breakdown"><RowLink href="#">Gross Revenue: $1,600</RowLink><RowLink href="#">Commission (10%): $160</RowLink><RowLink href="#">Operator Revenue: $1,440</RowLink><RowLink href="#">Settlement: After completion</RowLink></Section>
    <Section title="Quick Actions"><button className="btn" style={{width:'100%',marginBottom:8}}>Message All Passengers</button><button className="btn secondary" style={{width:'100%',marginBottom:8}}>Message Operator</button><button className="btn danger" style={{width:'100%'}}>Cancel Journey</button></Section>
  </div>
 </>
}

export function Analytics(){return <>
 <div className="kpi-grid">{kpis.map(x=><KpiCard key={x.label} {...x}/>)}</div>
 <div className="tabs">{['Overview','Geography','Routes','Destinations','Pickups','Operators','Vehicles','Captains','Trend Analysis','Comparison','Profitability'].map((x,i)=><a key={x} className={i===0?'active':''}>{x}</a>)}</div>
 <div className="dashboard-grid">
  <Section title="Performance by Geography"><table className="table"><thead><tr><th>Country</th><th>Trips</th><th>Revenue</th><th>Avg Rev / Trip</th><th>Commission</th><th>Load</th></tr></thead><tbody>{countries.map(c=><tr key={c[0]}><td>{c[0]}</td><td>{c[1]}</td><td>{c[2]}</td><td>{c[3]}</td><td>{c[4]}</td><td>{c[6]}</td></tr>)}</tbody></table></Section>
  <Section title="Revenue Trend"><div className="chart-placeholder"><div className="chart-line"/></div></Section>
  <Section title="Performance Highlights"><div className="notice-list"><div className="notice"><span>Revenue up 14.2%</span><b>+$352k</b></div><div className="notice"><span>Operator revenue up 13.1%</span><b>+$259k</b></div><div className="notice"><span>Load factor improved</span><b>+4.3pp</b></div></div></Section>
 </div>
 <div className="grid-4" style={{marginTop:12}}>{['Top Routes by Revenue','Top Operators by Revenue','Top Destinations by Demand','Bottom Operators by Cancellation Rate'].map((t,idx)=><Section key={t} title={t}><table className="table"><tbody>{(idx===1?operators.map(o=>[o.name,o.trips,o.revenue]):journeys.slice(0,4).map(j=>[j.route,j.seats,j.revenue])).map((r:any,i)=><tr key={i}><td>{i+1}</td><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td></tr>)}</tbody></table></Section>)}</div>
 </>}

export function Operators(){return <>
 <div className="toolbar"><input placeholder="Search operators..."/><select><option>All Countries</option></select><select><option>All Statuses</option></select><button className="btn">+ Add Operator</button></div>
 <div className="grid-2">{operators.map(o=><Section key={o.id} title={o.name} action={<Status value={o.status}/>}><div className="metric-pair"><div className="mini-metric"><small>Revenue (Net)</small><strong>{o.revenue}</strong></div><div className="mini-metric"><small>Trips</small><strong>{o.trips}</strong></div><div className="mini-metric"><small>Quality</small><strong>{o.quality}</strong></div><div className="mini-metric"><small>Load Factor</small><strong>{o.load}</strong></div></div><div style={{display:'flex',gap:8,marginTop:12}}><Link className="btn" href={`/admin/operators/${o.id}`}>View Operator</Link><Link className="btn secondary" href={`/admin/operators/${o.id}?operator=${o.id}`}>Manage as Operator</Link></div></Section>)}</div>
 </>}

export function OperatorDetail({id}:{id:string}){const o=operators.find(x=>x.id===id)||operators[0];return <>
 <Section title={`Managing operator: ${o.name}`} action={<Link className="btn" href={`/admin/operators/${o.id}?operator=${o.id}`}>Operator Dashboard</Link>}><div className="operator-header"><div className="operator-logo">{o.name.toUpperCase()}</div><div><h2 style={{margin:'0 0 5px'}}>{o.name} <Status value={o.status}/></h2><small>{o.country}</small><p style={{color:'var(--muted)',fontSize:12}}>Premium transport operator</p></div><div style={{marginLeft:'auto'}} className="metric-pair"><div className="mini-metric"><small>Revenue</small><strong>{o.revenue}</strong></div><div className="mini-metric"><small>Trips</small><strong>{o.trips}</strong></div></div></div></Section>
 <div className="tabs">{['Overview','Vehicles','Captains','Routes & Availability','Journeys','Earnings & Settlements','Quality & Performance','Staff & Access','Documents','Settings'].map((x,i)=><a key={x} className={i===0?'active':''}>{x}</a>)}</div>
 <div className="grid-3"><Section title="Operator Summary"><RowLink href="#">Base Country: {o.country}</RowLink><RowLink href="#">Vehicle Types: Speed Boat, Taxi Boat</RowLink><RowLink href="#">Total Vehicles: 5</RowLink><RowLink href="#">Active Captains: 6</RowLink><RowLink href="#">Active Routes: 8</RowLink></Section><Section title="Setup Progress"><Progress value={80}/><div className="setup-list" style={{marginTop:12}}>{['Operator Profile','Commission & Terms','Payment Details','Vehicle Types','Vehicles Added','Captains Added','Routes Configured','Availability Set','Documents Uploaded','Team Members'].map((x,i)=><div className="setup-item" key={x}><span>{x}</span><span className={i<8?'done':''}>{i<8?'Completed':'Pending'}</span></div>)}</div></Section><Section title="Quick Actions"><button className="btn" style={{width:'100%',marginBottom:8}}>Add Vehicle</button><button className="btn secondary" style={{width:'100%',marginBottom:8}}>Add Captain</button><button className="btn secondary" style={{width:'100%'}}>Assign Route</button></Section></div>
 <div className="grid-3" style={{marginTop:12}}><Section title="Top Performing Routes"><table className="table"><tbody>{journeys.slice(0,4).map(j=><tr key={j.id}><td>{j.route}</td><td>{j.revenue}</td><td>{j.load}%</td></tr>)}</tbody></table></Section><Section title="Top Vehicles by Revenue"><table className="table"><tbody>{['Barefoot 36','Island Rider','Coastal Taxi 2','Sea Breeze'].map((x,i)=><tr key={x}><td>{x}</td><td>{102-i*14} trips</td><td>${(126450-i*15800).toLocaleString()}</td></tr>)}</tbody></table></Section><Section title="Top Captains by Quality"><table className="table"><tbody>{['John Peters','Mike Joseph','David Lewis','Sarah Williams'].map((x,i)=><tr key={x}><td>{x}</td><td>{(89.6-i*2.3).toFixed(1)}</td></tr>)}</tbody></table></Section></div>
 </>}

export function Finance(){return <>
 <div className="grid-4"><KpiCard label="Revenue (Net)" value="$246,750" delta="12.6%"/><KpiCard label="Commission" value="$24,835" delta="10.4%"/><KpiCard label="Avg Commission Rate" value="10.08%"/><KpiCard label="Trips" value="128" delta="8.5%"/></div>
 <div className="grid-3" style={{marginTop:12}}><Section title="Revenue Trend"><div className="chart-placeholder"><div className="chart-line"/></div></Section><Section title="Settlements Overview"><div className="metric-pair"><div className="mini-metric"><small>Total to Settle</small><strong>$198,420</strong></div><div className="mini-metric"><small>Settled</small><strong>$142,680</strong></div></div><RowLink href="#">Paid $142,680</RowLink><RowLink href="#">Scheduled $28,300</RowLink><RowLink href="#">On Hold $12,880</RowLink></Section><Section title="Liabilities & Refunds"><RowLink href="#">Total Liabilities $32,480</RowLink><RowLink href="#">Refunds $14,230</RowLink><RowLink href="#">Reconciliation 98.1%</RowLink></Section></div>
 <Section title="Operator Financial Performance" className="" action={<button className="btn secondary">Export</button>}><table className="table"><thead><tr><th>Operator</th><th>Trips</th><th>Revenue</th><th>Avg Revenue / Trip</th><th>Commission</th><th>Avg Rate</th><th>Net Payable</th></tr></thead><tbody>{operators.map(o=><tr key={o.id}><td>{o.name}</td><td>{o.trips}</td><td>{o.revenue}</td><td>${Math.round(parseInt(o.revenue.replace(/[$,]/g,''))/o.trips).toLocaleString()}</td><td>{o.commission}</td><td>{o.commission}</td><td>{o.revenue}</td></tr>)}</tbody></table></Section>
 </>}

export function Network(){return <>
 <div className="grid-4"><KpiCard label="Countries" value="12"/><KpiCard label="Routes" value="128"/><KpiCard label="Pick Ups" value="426"/><KpiCard label="Destinations" value="184"/></div>
 <div className="grid-3" style={{marginTop:12}}><Section title="Countries">{['Antigua & Barbuda','Barbados','St. Kitts & Nevis','Grenada','Bahamas'].map((x,i)=><RowLink key={x} href="#">{x} · {28-i*3} routes</RowLink>)}</Section><Section title="Regions / Towns"><RowLink href="#">Antigua · 20 routes</RowLink><RowLink href="#">Barbuda · 6 routes</RowLink><RowLink href="#">Jolly Harbour · 6 routes</RowLink><RowLink href="#">St. John’s · 10 routes</RowLink></Section><Section title="Network Performance"><div className="metric-pair"><div className="mini-metric"><small>Revenue</small><strong>$246,750</strong></div><div className="mini-metric"><small>Total Trips</small><strong>1,248</strong></div></div><div className="chart-placeholder" style={{height:160,marginTop:10}}><div className="chart-line"/></div></Section></div>
 <Section title="Routes" action={<button className="btn">+ Add Route</button>}><table className="table"><thead><tr><th>Route</th><th>Type</th><th>Trips</th><th>Revenue</th><th>Avg Rev / Trip</th><th>Load</th><th>Status</th></tr></thead><tbody>{journeys.map(j=><tr key={j.id}><td>{j.route}</td><td>{j.type}</td><td>{Math.round(parseInt(j.seats)*17+45)}</td><td>{j.revenue}</td><td>{j.revenue}</td><td>{j.load}%</td><td><Status value="ACTIVE"/></td></tr>)}</tbody></table></Section>
 </>}

export function Support(){return <div className="grid-3"><Section title="Support Inbox"><div className="toolbar"><input placeholder="Search conversations"/></div>{['Emma Johnson · Booking change request','Island Rider · Trip cancellation question','John Peters · Late running message','Sarah Williams · Refund not received','Coastal Taxi · Vehicle update'].map((x,i)=><RowLink href="#" key={x}>{x} · {i<2?'Urgent':'Open'}</RowLink>)}</Section><Section title="Support Analytics"><div className="metric-pair"><div className="mini-metric"><small>Total Tickets</small><strong>128</strong></div><div className="mini-metric"><small>Open Tickets</small><strong>24</strong></div><div className="mini-metric"><small>Avg First Response</small><strong>18m</strong></div><div className="mini-metric"><small>Resolution Rate</small><strong>92%</strong></div></div><div className="chart-placeholder" style={{height:180,marginTop:12}}><div className="chart-line"/></div></Section><Section title="Administration"><RowLink href="#">Commissions & Fees</RowLink><RowLink href="#">Payment Providers</RowLink><RowLink href="#">Cancellation Policies</RowLink><RowLink href="#">User Management</RowLink><RowLink href="#">Roles & Permissions</RowLink><RowLink href="#">Audit Log</RowLink></Section></div>}

export function OperatorMobile(){return <div className="grid-2"><Section title="Barefoot Dashboard"><div className="grid-3"><div className="mini-metric"><small>Confirmed</small><strong>5</strong></div><div className="mini-metric"><small>At Risk</small><strong>1</strong></div><div className="mini-metric"><small>Action Needed</small><strong>0</strong></div></div><div className="metric-pair" style={{marginTop:10}}><div className="mini-metric"><small>Revenue (Net)</small><strong>$412,850</strong></div><div className="mini-metric"><small>Quality</small><strong>84.7</strong></div></div></Section><Section title="Next Journey"><RowLink href="#">08:30 Jolly Harbour → Nobu · 6/8 seats</RowLink><RowLink href="#">11:00 Airport → Jolly Harbour · 4/4 seats</RowLink><RowLink href="#">14:00 Falmouth → Montego Bay · At Risk</RowLink></Section></div>}

export function CaptainMobile(){return <div className="grid-2"><Section title="Today's Journeys"><RowLink href="#">08:30 Jolly Harbour → Nobu · 6/8 seats</RowLink><RowLink href="#">12:30 Nobu → Jolly Harbour · 4/8 seats</RowLink><RowLink href="#">16:45 Jolly Harbour → Falmouth · Completed</RowLink></Section><Section title="Next Journey"><Status value="CONFIRMED"/><h2>08:30 Jolly Harbour → Nobu</h2><p>Barefoot 36 · 6 passengers</p><button className="btn" style={{width:'100%'}}>Start Journey</button></Section></div>}

export function CustomerSearch(){return <div className="grid-2"><Section title="Search Routes"><div className="toolbar"><select><option>Jolly Harbour, Antigua</option></select><select><option>Nobu, Barbuda</option></select><select><option>2 Adults</option></select><button className="btn">Search Routes</button></div></Section><Section title="Available Journeys">{journeys.slice(0,4).map(j=><RowLink href="#" key={j.id}>{j.time} · {j.route} · {j.revenue}</RowLink>)}</Section></div>}
