'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { getSupabaseBrowserClient } from '@/lib/supabase';
import { loadAdminJourneys,loadAdminLiveOperationsDetail,loadAdminJourneyBookings,loadAdminJourneyAllocations,loadRoutePerformance,loadCountryPerformance,loadDestinationPerformance,loadOperatorPerformance,loadCaptains,loadCountries,loadDestinations,loadOperators,loadPickups,loadRoutes,loadSettlements,loadSupportInbox,loadVehicles,loadOperatorJourneys,loadCustomerBookings,loadVehicleTypes,loadVehicleRouteOffers,loadVehicleUnavailability,adminAutoAssignCaptain,adminAssignCaptain,adminRefreshConsiderations,adminCancelBooking,adminRegisterOperatorCancellation,adminCreateVehicle,adminCreateCaptain,adminSetCaptainVehicleType,adminCreateRouteOffer,adminSetRouteOfferActive,adminAddVehicleUnavailability } from '@/lib/data';
import { KpiCard, RowLink, Section, Status } from './ui';
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((c||0)/100);
const date=(x:any)=>x?new Date(x).toLocaleString():'—';
function useLoad(fn:any){const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''); useEffect(()=>{fn().then((r:any)=>{setRows(r.data||[]);setError(r.error?.message||'')})},[]); return {rows,error}}
function AdminJourneyActions({journey,allocations,bookings,onChanged}:{journey:any,allocations:any[],bookings:any[],onChanged:()=>void}){
 const {rows:captains}=useLoad(loadCaptains); const [busy,setBusy]=useState(''); const [msg,setMsg]=useState('');
 const run=async(label:string,fn:()=>Promise<any>)=>{setBusy(label);setMsg('');const r=await fn();setBusy('');if(r.error)setMsg(r.error.message||String(r.error));else{setMsg(label+' completed');onChanged()}};
 const assign=(a:any)=>{const eligible=captains.filter(c=>c.operator_id===a.operator_id&&c.active); const current=a.captain_id||''; return <div className="admin-action-row" key={a.confirmed_allocation_id}><div><b>{a.operator_name}</b><small>{a.vehicle_name}</small></div><select defaultValue={current} id={`capt-${a.confirmed_allocation_id}`}><option value="">Select captain</option>{eligible.map(c=><option value={c.id} key={c.id}>{c.first_name} {c.last_name}</option>)}</select><button className="btn secondary" disabled={!!busy} onClick={()=>{const el=document.getElementById(`capt-${a.confirmed_allocation_id}`) as HTMLSelectElement; if(el?.value)run('Captain assignment',()=>adminAssignCaptain(a.confirmed_allocation_id,el.value,'Assigned by Site Admin from Journey Detail'))}}>Assign</button><button className="btn secondary" disabled={!!busy} onClick={()=>run('Auto captain assignment',()=>adminAutoAssignCaptain(a.confirmed_allocation_id))}>Auto</button></div>};
 return <div className="admin-actions"><h3>Site Admin operational controls</h3><p className="data-note">These controls use protected V2 business functions. They do not bypass allocation, cancellation or settlement rules.</p>{allocations.map(assign)}<div className="admin-action-row"><div><b>Allocation engine</b><small>Re-evaluate eligible vehicles / considerations</small></div><button className="btn secondary" disabled={!!busy} onClick={()=>run('Considerations refresh',()=>adminRefreshConsiderations(journey.departure_id))}>Refresh considerations</button></div>{allocations.map(a=><div className="admin-action-row danger-zone" key={'cancel-'+a.confirmed_allocation_id}><div><b>{a.operator_name} cancellation</b><small>Creates the operator cancellation/liability record</small></div><button className="btn danger" disabled={!!busy} onClick={()=>{const reason=window.prompt(`Reason for cancelling ${a.operator_name}'s confirmed allocation?`);if(reason&&window.confirm('Register this operator cancellation? This is an operational/financial action.'))run('Operator cancellation',()=>adminRegisterOperatorCancellation(a.confirmed_allocation_id,0,0,reason))}}>Register cancellation</button></div>)}{bookings.filter(b=>!['cancelled','refunded'].includes(String(b.booking_status))).map(b=><div className="admin-action-row" key={'book-'+b.booking_id}><div><b>{b.customer_name||'Customer'} · {b.seats} seat(s)</b><small>{money(b.total_price_cents)} booking</small></div><button className="btn danger" disabled={!!busy} onClick={()=>{const reason=window.prompt('Cancellation/refund reason?');if(!reason)return;const raw=window.prompt('Requested refund amount in USD','0');if(raw===null)return;const cents=Math.round(Number(raw)*100);if(Number.isFinite(cents)&&cents>=0&&window.confirm(`Cancel booking and request ${money(cents)} refund?`))run('Booking cancellation/refund request',()=>adminCancelBooking(b.booking_id,cents,reason))}}>Cancel / refund</button></div>)}{msg&&<p className={msg.includes('completed')?'action-success':'action-error'}>{msg}</p>}</div>
}
export function JourneyDetail({id}:{id:string}){
  const {rows:detail,error:detailError}=useLoad(loadAdminLiveOperationsDetail);
  const {rows:bookings,error:bookingError}=useLoad(loadAdminJourneyBookings);
  const {rows:allocations,error:allocationError}=useLoad(loadAdminJourneyAllocations);
  const j=detail.find(x=>x.departure_id===id);
  const jb=bookings.filter(x=>x.departure_id===id);
  const ja=allocations.filter(x=>x.departure_id===id);
  const err=detailError||bookingError||allocationError;
  if(!j)return <Section title="Journey"><div className="empty-state">Loading journey or no access…</div></Section>;
  const totalCustomerRevenue=jb.reduce((n,x)=>n+Number(x.total_price_cents||0),0);
  const operatorValue=ja.reduce((n,x)=>n+Number(x.operator_journey_value_cents||0),0);
  const commission=ja.reduce((n,x)=>n+Number(x.pace_shuttles_commission_cents||0),0);
  const operatorNet=ja.reduce((n,x)=>n+Number(x.operator_net_before_adjustments_cents||0),0);
  return <>
    {err&&<p className="data-note">{err}</p>}
    <section className="card hero-strip">
      <div className="hero-cell"><small>Route</small><strong>{j.route_name}</strong><small>{[j.locality_name,j.region_name,j.country_name].filter(Boolean).join(' · ')||j.trip_timezone}</small></div>
      <div className="hero-cell"><small>Journey ID</small><strong>{j.departure_id.slice(0,8)}</strong></div>
      <div className="hero-cell"><small>Departure</small><strong>{date(j.scheduled_departure_ts)}</strong></div>
      <div className="hero-cell"><small>Bookings</small><strong>{j.booking_count}</strong></div>
      <div className="hero-cell"><small>Seats</small><strong>{j.booked_seats}</strong></div>
      <div className="hero-cell"><small>Vehicles</small><strong>{j.confirmed_vehicle_count}</strong></div>
      <div className="hero-cell"><small>Captains</small><strong>{j.active_captain_count}</strong></div>
      <div className="hero-cell"><small>Status</small><strong><Status value={String(j.departure_status).replaceAll('_',' ').toUpperCase()}/></strong></div>
    </section>

    <div className="grid-4" style={{marginTop:12}}>
      <div className="mini-metric"><small>Customer revenue</small><strong>{money(totalCustomerRevenue)}</strong></div>
      <div className="mini-metric"><small>Operator journey value</small><strong>{money(operatorValue)}</strong></div>
      <div className="mini-metric"><small>Pace commission</small><strong>{money(commission)}</strong></div>
      <div className="mini-metric"><small>Operator net</small><strong>{money(operatorNet)}</strong></div>
    </div>

    <div className="grid-3" style={{marginTop:12}}>
      <Section title="Operational Timeline">
        <RowLink href="#">T-72: {date(j.t72_ts)}</RowLink>
        <RowLink href="#">T-24: {date(j.t24_ts)}</RowLink>
        <RowLink href="#">Departure: {date(j.scheduled_departure_ts)}</RowLink>
        <RowLink href="#">Arrival: {date(j.scheduled_arrival_ts)}</RowLink>
      </Section>
      <Section title="Allocation & Crew">
        {ja.length?ja.map(x=><div className="notice" key={x.confirmed_allocation_id}><span><b>{x.operator_name}</b><br/>{x.vehicle_name}<br/><small>{x.captain_name||'No captain assigned'}</small></span><span><Status value={String(x.allocation_status||'CONFIRMED').toUpperCase()}/><br/><small>{((Number(x.effective_commission_bps||0))/100).toFixed(2)}% commission</small></span></div>):<div className="empty-state">No confirmed allocation.</div>}
      </Section>
      <Section title="Status & Admin">
        <div className="notice-list">
          {j.at_risk_reason&&<div className="notice warn"><span>At-risk reason</span><b>{j.at_risk_reason}</b></div>}
          {j.cancelled_reason&&<div className="notice bad"><span>Cancellation reason</span><b>{j.cancelled_reason}</b></div>}
          {!j.at_risk_reason&&!j.cancelled_reason&&<div className="notice"><span>Operational status</span><b>{String(j.departure_status).replaceAll('_',' ')}</b></div>}
        </div>
        <AdminJourneyActions journey={j} allocations={ja} bookings={jb} onChanged={()=>window.location.reload()}/>
      </Section>
    </div>

    <div className="grid-2" style={{marginTop:12}}>
      <Section title={`Bookings & Passenger Groups (${jb.length})`}>
        <table className="table"><thead><tr><th>Lead customer</th><th>Status</th><th>Seats</th><th>Unit price</th><th>Total</th><th>Paid</th></tr></thead><tbody>
          {jb.map(x=><tr key={x.booking_id}><td><b>{x.customer_name||x.lead_last_name||'Customer'}</b></td><td><Status value={String(x.booking_status).replaceAll('_',' ').toUpperCase()}/></td><td>{x.seats}</td><td>{money(x.unit_price_cents)}</td><td>{money(x.total_price_cents)}</td><td>{x.paid_at?'Yes':'No'}</td></tr>)}
          {!jb.length&&<tr><td colSpan={6} className="empty-state">No bookings for this journey.</td></tr>}
        </tbody></table>
      </Section>
      <Section title="Journey Financial Reconciliation">
        <div className="metric-pair">
          <div className="mini-metric"><small>Customer revenue</small><strong>{money(totalCustomerRevenue)}</strong></div>
          <div className="mini-metric"><small>Operator journey value</small><strong>{money(operatorValue)}</strong></div>
          <div className="mini-metric"><small>Pace commission</small><strong>{money(commission)}</strong></div>
          <div className="mini-metric"><small>Operator net</small><strong>{money(operatorNet)}</strong></div>
        </div>
        <p className="data-note">Customer revenue is what customers paid for the journey. Operator journey value is the amount used for operator settlement/commission calculations. They are intentionally shown separately.</p>
      </Section>
    </div>
  </>;
}
export function Analytics(){
 const {rows:j}=useLoad(loadAdminJourneys),{rows:c}=useLoad(loadCountryPerformance),{rows:r}=useLoad(loadRoutePerformance),{rows:d}=useLoad(loadDestinationPerformance),{rows:o}=useLoad(loadOperatorPerformance);
 const gross=r.reduce((n,x)=>n+Number(x.customer_revenue_cents||0),0),commission=r.reduce((n,x)=>n+Number(x.pace_commission_cents||0),0),operatorValue=r.reduce((n,x)=>n+Number(x.operator_journey_value_cents||0),0);
 const topRoutes=[...r].sort((a,b)=>Number(b.customer_revenue_cents||0)-Number(a.customer_revenue_cents||0));
 const topOps=[...o].sort((a,b)=>Number(b.operator_journey_value_cents||0)-Number(a.operator_journey_value_cents||0));
 const topDest=[...d].sort((a,b)=>Number(b.customer_revenue_cents||0)-Number(a.customer_revenue_cents||0));
 return <><div className="grid-4"><KpiCard label="Journeys" value={String(j.length)}/><KpiCard label="Customer Revenue" value={money(gross)}/><KpiCard label="Pace Commission" value={money(commission)}/><KpiCard label="Avg Commission Rate" value={operatorValue?`${(commission/operatorValue*100).toFixed(2)}%`:'—'}/></div>
 <div className="grid-2" style={{marginTop:12}}><Section title="Performance by Country"><table className="table"><thead><tr><th>Country</th><th>Trips</th><th>Customer revenue</th><th>Avg / trip</th><th>Operator value</th><th>Commission</th></tr></thead><tbody>{[...c].sort((a,b)=>Number(b.customer_revenue_cents||0)-Number(a.customer_revenue_cents||0)).map(x=><tr key={x.country_id}><td><b>{x.country_name}</b></td><td>{x.trips}</td><td>{money(x.customer_revenue_cents)}</td><td>{money(x.avg_customer_revenue_per_trip_cents)}</td><td>{money(x.operator_journey_value_cents)}</td><td>{money(x.pace_commission_cents)}</td></tr>)}</tbody></table></Section>
 <Section title="Journey Status"><div className="notice-list">{Object.entries(j.reduce((a:any,x:any)=>{const k=String(x.departure_status);a[k]=(a[k]||0)+1;return a},{})).map(([k,v])=><div className="notice" key={k}><span>{k.replaceAll('_',' ')}</span><b>{String(v)}</b></div>)}</div></Section></div>
 <div className="grid-3" style={{marginTop:12}}><Section title="Top Routes by Customer Revenue">{topRoutes.slice(0,8).map((x,i)=><div className="notice" key={x.route_id}><span>{i+1}. {x.route_name}<br/><small>{x.trips} trip(s) · avg {money(x.avg_customer_revenue_per_trip_cents)}</small></span><b>{money(x.customer_revenue_cents)}</b></div>)}</Section><Section title="Top Operators by Journey Value">{topOps.slice(0,8).map((x,i)=><div className="notice" key={x.operator_id}><span>{i+1}. {x.operator_name}<br/><small>{x.trips} trip(s) · avg {money(x.avg_operator_revenue_per_trip_cents)}</small></span><b>{money(x.operator_journey_value_cents)}</b></div>)}</Section><Section title="Top Destinations by Customer Revenue">{topDest.slice(0,8).map((x,i)=><div className="notice" key={x.destination_id}><span>{i+1}. {x.destination_name}<br/><small>{x.trips} trip(s) · avg {money(x.avg_customer_revenue_per_trip_cents)}</small></span><b>{money(x.customer_revenue_cents)}</b></div>)}</Section></div>
 <div className="grid-2" style={{marginTop:12}}><Section title="Bottom Routes by Revenue">{[...topRoutes].reverse().slice(0,8).map(x=><div className="notice" key={x.route_id}><span>{x.route_name}</span><b>{money(x.customer_revenue_cents)}</b></div>)}</Section><Section title="Operator Quality & Commission">{[...o].sort((a,b)=>Number(b.quality_score||0)-Number(a.quality_score||0)).map(x=><div className="notice" key={x.operator_id}><span>{x.operator_name}<br/><small>{x.trips} trip(s) · {x.avg_commission_rate_pct==null?'—':Number(x.avg_commission_rate_pct).toFixed(2)+'%'} avg commission</small></span><b>{x.quality_score??'—'}</b></div>)}</Section></div></>}
export function Operators(){const {rows,error}=useLoad(loadOperators); return <>{error&&<p className="data-note">{error}</p>}<Section title="Operators" action={<button className="btn">+ Add Operator</button>}><table className="table"><thead><tr><th>Operator</th><th>Town / Region</th><th>Quality</th><th>Stripe</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><b>{o.name}</b></td><td>{[o.town,o.region].filter(Boolean).join(', ')||'—'}</td><td>{o.quality_score??'—'}</td><td>{o.stripe_onboarding_status||'—'}</td><td><Status value={o.active?'ACTIVE':'INACTIVE'}/></td><td><Link href={`/admin/operators/${o.id}`}>Manage →</Link></td></tr>)}</tbody></table></Section></>}
export function OperatorDetail({id}:{id:string}){
 const {rows:o}=useLoad(loadOperators),{rows:v}=useLoad(loadVehicles),{rows:c}=useLoad(loadCaptains),{rows:types}=useLoad(loadVehicleTypes),{rows:routes}=useLoad(loadRoutes),{rows:offers}=useLoad(loadVehicleRouteOffers),{rows:unavail}=useLoad(loadVehicleUnavailability);
 const [msg,setMsg]=useState(''); const x=o.find(z=>z.id===id); if(!x)return <Section title="Operator"><div className="empty-state">Loading operator…</div></Section>; const vv=v.filter(z=>z.operator_id===id),cc=c.filter(z=>z.operator_id===id),oo=offers.filter(z=>z.operator_id===id),uu=unavail.filter(z=>z.operator_id===id);
 const done=(r:any,label:string)=>{if(r.error)setMsg(r.error.message);else{setMsg(label+' created');window.setTimeout(()=>window.location.reload(),500)}};
 return <><Section title={x.name} action={<Link className="btn" href={`/admin/operators/${id}?operator=${encodeURIComponent(x.name)}`}>Manage as Operator</Link>}><div className="grid-4"><div className="mini-metric"><small>Quality</small><strong>{x.quality_score??'—'}</strong></div><div className="mini-metric"><small>Vehicles</small><strong>{vv.length}</strong></div><div className="mini-metric"><small>Captains</small><strong>{cc.length}</strong></div><div className="mini-metric"><small>Status</small><strong>{x.active?'Active':'Inactive'}</strong></div></div></Section>
 <div className="grid-2" style={{marginTop:12}}><Section title="Fleet" action={<button className="btn secondary" onClick={async()=>{const name=window.prompt('Vehicle name');if(!name)return;const type=types[0];if(!type){setMsg('No active vehicle type found');return}const min=Number(window.prompt('Minimum seats','4'));const max=Number(window.prompt('Maximum seats','12'));const revenue=Number(window.prompt('Minimum journey revenue (USD)','1000'));done(await adminCreateVehicle({p_operator_id:id,p_vehicle_type_id:type.id,p_name:name,p_description:null,p_min_seats:min,p_max_seats:max,p_min_revenue_cents:Math.round(revenue*100),p_min_value_threshold_ratio:null,p_max_seat_discount_bps:0}),'Vehicle')}}>+ Add Vehicle</button>}>{vv.map(z=><RowLink href="#" key={z.id}>{z.name} · {z.default_min_seats??'—'}–{z.default_max_seats??'—'} seats</RowLink>)}{!vv.length&&<div className="empty-state">No vehicles.</div>}</Section>
 <Section title="Captains" action={<button className="btn secondary" onClick={async()=>{const first=window.prompt('Captain first name');if(!first)return;const last=window.prompt('Captain last name');if(!last)return;done(await adminCreateCaptain({p_operator_id:id,p_first_name:first,p_last_name:last,p_email:null,p_phone:null,p_notes:'Created by Site Admin'}),'Captain')}}>+ Add Captain</button>}>{cc.map(z=><RowLink href="#" key={z.id}>{z.first_name} {z.last_name} · {z.active?'Active':'Inactive'}</RowLink>)}{!cc.length&&<div className="empty-state">No captains.</div>}</Section></div>
 <div className="grid-2" style={{marginTop:12}}><Section title="Route Assignments" action={<button className="btn secondary" onClick={async()=>{const vehicle=vv[0],route=routes[0];if(!vehicle||!route){setMsg('Add a vehicle and ensure a route exists first');return}done(await adminCreateRouteOffer({p_vehicle_id:vehicle.id,p_route_id:route.id,p_min_seats:vehicle.default_min_seats,p_max_seats:vehicle.default_max_seats,p_min_revenue_cents:vehicle.default_min_revenue_cents,p_preferred:false,p_min_value_threshold_ratio:vehicle.default_min_value_threshold_ratio,p_post_min_discount_enabled:false,p_post_min_discount_bps:0}),'Route assignment')}}>+ Assign Route</button>}>{oo.map(z=><div className="notice" key={z.id}><span><b>{z.vehicle_name}</b><br/><small>{z.route_name} · {z.min_seats}–{z.max_seats} seats · {money(z.min_revenue_cents)} min</small></span><Status value={z.active?'ACTIVE':'INACTIVE'}/></div>)}{!oo.length&&<div className="empty-state">No route assignments.</div>}</Section>
 <Section title="Vehicle Unavailability">{uu.map(z=><div className="notice" key={z.id}><span><b>{z.vehicle_name}</b><br/><small>{date(z.start_ts)} → {date(z.end_ts)}</small></span><span>{z.reason_code||'Unavailable'}</span></div>)}{!uu.length&&<div className="empty-state">No availability exceptions.</div>}</Section></div>{msg&&<p className="data-note">{msg}</p>}</>}
export function Finance(){const {rows:s}=useLoad(loadSettlements),{rows:o}=useLoad(loadOperators); const total=s.reduce((n,x)=>n+Number(x.journey_value_cents||0),0),comm=s.reduce((n,x)=>n+Number(x.commission_cents||0),0),net=s.reduce((n,x)=>n+Number(x.net_payable_cents||0),0); return <><div className="grid-4"><KpiCard label="Journey Value" value={money(total)}/><KpiCard label="Pace Commission" value={money(comm)}/><KpiCard label="Net Payable" value={money(net)}/><KpiCard label="Settlements" value={String(s.length)}/></div><Section title="Settlements"><table className="table"><thead><tr><th>Operator</th><th>Journey Value</th><th>Commission</th><th>Rate</th><th>Net Payable</th><th>Status</th></tr></thead><tbody>{s.map(x=><tr key={x.id}><td>{o.find(z=>z.id===x.operator_id)?.name||x.operator_id?.slice(0,8)}</td><td>{money(x.journey_value_cents)}</td><td>{money(x.commission_cents)}</td><td>{((x.effective_commission_bps||0)/100).toFixed(2)}%</td><td>{money(x.net_payable_cents)}</td><td><Status value={String(x.status).toUpperCase()}/></td></tr>)}</tbody></table></Section></>}
export function Network(){const {rows:c}=useLoad(loadCountries),{rows:r}=useLoad(loadRoutes),{rows:d}=useLoad(loadDestinations),{rows:p}=useLoad(loadPickups); return <><div className="grid-4"><KpiCard label="Countries" value={String(c.length)}/><KpiCard label="Routes" value={String(r.length)}/><KpiCard label="Pick Ups" value={String(p.length)}/><KpiCard label="Destinations" value={String(d.length)}/></div><div className="grid-2" style={{marginTop:12}}><Section title="Countries">{c.map(x=><RowLink href="#" key={x.id}>{x.name} · {x.active?'Active':'Inactive'}</RowLink>)}</Section><Section title="Routes"><table className="table"><thead><tr><th>Route</th><th>Timezone</th><th>Status</th></tr></thead><tbody>{r.map(x=><tr key={x.id}><td>{x.route_name}</td><td>{x.trip_timezone}</td><td><Status value={x.is_active?'ACTIVE':'INACTIVE'}/></td></tr>)}</tbody></table></Section></div></>}
export function Support(){const {rows}=useLoad(loadSupportInbox); return <div className="grid-2"><Section title="Support Inbox">{rows.map(x=><RowLink href="#" key={x.conversation_id}>{x.ticket_number?`#${x.ticket_number} · `:''}{x.category||x.channel} · {x.ticket_status||x.conversation_status}</RowLink>)}{!rows.length&&<div className="empty-state">No support items.</div>}</Section><Section title="Administration"><RowLink href="/admin/settings">Commissions & Fees</RowLink><RowLink href="/admin/settings">Cancellation Policies</RowLink><RowLink href="/admin/settings">Roles & Permissions</RowLink><RowLink href="/admin/settings">Payment Providers</RowLink></Section></div>}
export function OperatorMobile(){const {rows}=useLoad(loadOperatorJourneys); return <Section title="Operator Journeys">{rows.map(x=><RowLink href="#" key={x.confirmed_allocation_id}>{date(x.scheduled_departure_ts)} · {x.route_name} · {money(x.operator_net_before_adjustments_cents)}</RowLink>)}{!rows.length&&<div className="empty-state">No operator journeys visible for this account.</div>}</Section>}
export function CaptainMobile(){return <div className="grid-2"><Section title="Captain App"><p>Captain authentication and journey execution will use the existing V2 captain functions.</p><p className="data-note">This screen is intentionally locked until a captain identity is linked to an authenticated user.</p></Section><Section title="Safety"><p>Start/complete journey controls will only be enabled for the captain assigned to the confirmed allocation.</p></Section></div>}
export function CustomerSearch(){const {rows}=useLoad(loadCustomerBookings); return <Section title="My Bookings">{rows.map(x=><RowLink href="#" key={x.booking_id}>{date(x.scheduled_departure_ts)} · {x.route_name} · {x.seats} seat(s) · {money(x.total_price_cents)}</RowLink>)}{!rows.length&&<div className="empty-state">No bookings visible for this signed-in user.</div>}</Section>}
