'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import {buildPartnerApplicationPayload,validatePartnerApplication} from '@/lib/partner-application';
import {loadPartnerFormCountries,loadPartnerFormDestinationTypes,loadPartnerFormPlaces,loadPartnerFormTransportTypes,submitPartnerApplication} from '@/lib/data';
const initial:any={application_type:'operator',org_name:'',country_id:'',other_country_text:'',transport_type_id:'',destination_type_id:'',place_ids:[]};
export function PartnerApplicationForm(){
 const [form,setForm]=useState(initial),[countries,setCountries]=useState<any[]>([]),[types,setTypes]=useState<any[]>([]),[destinationTypes,setDestinationTypes]=useState<any[]>([]),[places,setPlaces]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reference,setReference]=useState('');
 useEffect(()=>{Promise.all([loadPartnerFormCountries(),loadPartnerFormTransportTypes(),loadPartnerFormDestinationTypes(),loadPartnerFormPlaces()]).then(([c,t,d,p])=>{setCountries(c.data);setTypes(t.data);setDestinationTypes(d.data);setPlaces(p.data);setMessage(c.error?.message||t.error?.message||d.error?.message||p.error?.message||'')})},[]);
 const set=(name:string,value:any)=>setForm((f:any)=>({...f,[name]:value}));
 const submit=async(e:FormEvent)=>{e.preventDefault();const errors=validatePartnerApplication(form);if(errors.length)return setMessage(errors.join('. '));setBusy(true);setMessage('');const r=await submitPartnerApplication(buildPartnerApplicationPayload(form));setBusy(false);if(r.error)return setMessage(r.error.message);setReference(String(r.data).slice(0,8).toUpperCase())};
 if(reference)return <main className="partner-page"><section className="partner-card partner-success"><h1>Application received</h1><p>Site Admin will review your application.</p><p>Your reference is <strong>{reference}</strong>.</p><Link className="ps-primary" href="/">Return home</Link></section></main>;
 const operator=form.application_type==='operator',filteredPlaces=places.filter(x=>x.transport_type_id===form.transport_type_id);
 const input=(name:string,label:string,type='text')=><label>{label}<input name={name} type={type} value={form[name]||''} onChange={e=>set(name,e.target.value)}/></label>;
 return <main className="partner-page"><header><Link href="/">← Pace Shuttles</Link><h1>Partner with Pace Shuttles</h1><p>Apply as an operator or destination. Remaining publication details can be completed with our team after review.</p></header><form className="partner-card" onSubmit={submit}>
 <div className="partner-switch"><button type="button" className={operator?'active':''} onClick={()=>set('application_type','operator')}>Operator</button><button type="button" className={!operator?'active':''} onClick={()=>set('application_type','destination')}>Destination</button></div>
 <h2>Organisation</h2><div className="partner-grid">{input('org_name','Organisation name *')}<label>Country *<select name="country_id" value={form.country_id||''} onChange={e=>set('country_id',e.target.value)}><option value="">Other / select</option>{countries.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{!form.country_id&&input('other_country_text','Other country *')}<label className="wide-field">Address<textarea name="org_address" value={form.org_address||''} onChange={e=>set('org_address',e.target.value)}/></label></div>
 <h2>{operator?'Operator details':'Destination details'}</h2><div className="partner-grid">{operator?<><label>Transport type *<select name="transport_type_id" value={form.transport_type_id||''} onChange={e=>{set('transport_type_id',e.target.value);set('place_ids',[])}}><option value="">Select</option>{types.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{input('fleet_size','Fleet size','number')}<fieldset className="wide-field"><legend>Places served</legend>{filteredPlaces.map(x=><label className="partner-check" key={x.id}><input type="checkbox" checked={(form.place_ids||[]).includes(x.id)} onChange={e=>set('place_ids',e.target.checked?[...(form.place_ids||[]),x.id]:(form.place_ids||[]).filter((id:string)=>id!==x.id))}/>{x.name}</label>)}</fieldset></>:<label>Destination type *<select name="destination_type_id" value={form.destination_type_id||''} onChange={e=>set('destination_type_id',e.target.value)}><option value="">Select</option>{destinationTypes.map(x=><option key={x.id} value={x.id}>{x.type}</option>)}</select></label>}<label className="wide-field">Suggested pickup points<textarea name="pickup_suggestions" value={form.pickup_suggestions||''} onChange={e=>set('pickup_suggestions',e.target.value)}/></label><label className="wide-field">Suggested destinations<textarea name="destination_suggestions" value={form.destination_suggestions||''} onChange={e=>set('destination_suggestions',e.target.value)}/></label></div>
 <h2>Contact and background</h2><div className="partner-grid">{input('telephone','Telephone')}{input('mobile','Mobile')}{input('email','Email','email')}{input('website','Website')}{input('contact_name','Contact name')}{input('contact_role','Contact role')}{input('social_instagram','Instagram')}{input('social_youtube','YouTube')}{input('social_x','X')}{input('social_facebook','Facebook')}{input('years_operation','Years in operation','number')}<label className="wide-field">Tell us about the organisation<textarea name="description" value={form.description||''} onChange={e=>set('description',e.target.value)}/></label></div>
 {message&&<p className="partner-error">{message}</p>}<button className="ps-primary" disabled={busy}>{busy?'Submitting…':'Submit application'}</button></form></main>
}
