import {NextResponse} from 'next/server';

type RpcClient={rpc:(name:string,args?:Record<string,unknown>)=>PromiseLike<{data:any;error:{message:string}|null}>};
type Dependencies={env:NodeJS.ProcessEnv;now:()=>string;createUserClient:(url:string,key:string,token:string)=>RpcClient;createServiceClient:(url:string,key:string)=>RpcClient;dispatchDueCustomerEmails:(limit?:number)=>Promise<{claimed:number;sent:number;failed:number}>};

const reply=(body:unknown,status=200)=>NextResponse.json(body,{status});
const safeError=(error:unknown)=>error instanceof Error?error.message:'Request failed';

export function createAdminSchedulerHandler(deps:Dependencies){
 const run=async(client:RpcClient,source:'catch_up'|'manual')=>{const asOf=deps.now();const begin=await client.rpc('v2_system_scheduler_begin',{p_execution_source:source,p_requested_at:asOf});if(begin.error)throw new Error(begin.error.message);const row=Array.isArray(begin.data)?begin.data[0]:begin.data,runId=String(row?.run_id||'');if(!runId)throw new Error('Scheduler run could not be started');if(row.enabled===false)return {status:'paused',runId};try{const operations=await client.rpc('v2_system_run_scheduled_operations',{p_t72_limit:100,p_t24_limit:100});if(operations.error)throw new Error(operations.error.message);const t24=await client.rpc('v2_system_schedule_t24_journey_notifications',{p_as_of:asOf});if(t24.error)throw new Error(t24.error.message);const feedback=await client.rpc('v2_system_schedule_feedback_requests',{p_as_of:asOf,p_limit:100});if(feedback.error)throw new Error(feedback.error.message);const emails=await deps.dispatchDueCustomerEmails(25),result={operations:operations.data,t24_queued:t24.data,feedback_queued:feedback.data,emails};const finish=await client.rpc('v2_system_scheduler_finish',{p_run_id:runId,p_result:result,p_failure_reason:null});if(finish.error)throw new Error(finish.error.message);return {status:'completed',runId,...result}}catch(error){await client.rpc('v2_system_scheduler_finish',{p_run_id:runId,p_result:{},p_failure_reason:safeError(error)});throw error}};
 return async(req:Request)=>{const token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'').trim();if(!token)return reply({error:'Unauthorized'},401);const url=deps.env.NEXT_PUBLIC_SUPABASE_URL,key=deps.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,serviceKey=deps.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||!serviceKey)return reply({error:'Server configuration incomplete'},500);const user=deps.createUserClient(url,key,token),service=deps.createServiceClient(url,serviceKey);
  try{if(req.method==='GET'){const now=new Date(deps.now()),from=new Date(now.getTime()-7*86400000).toISOString(),to=new Date(now.getTime()+60*86400000).toISOString();const [dashboard,events]=await Promise.all([user.rpc('v2_site_admin_scheduler_dashboard'),user.rpc('v2_site_admin_scheduled_event_calendar',{p_from:from,p_to:to})]);if(dashboard.error||events.error)return reply({error:(dashboard.error||events.error)?.message||'Site Admin access required'},403);return reply({dashboard:dashboard.data,events:events.data||[]})}
   if(req.method!=='POST')return reply({error:'Method not allowed'},405);const body=await req.json().catch(()=>null) as any;if(!body?.action)return reply({error:'Action is required'},400);
   if(body.action==='set_enabled'){if(typeof body.enabled!=='boolean')return reply({error:'Enabled state is required'},400);const changed=await user.rpc('v2_site_admin_set_scheduler_enabled',{p_enabled:body.enabled,p_reason:String(body.reason||'')||null});if(changed.error)return reply({error:changed.error.message},403);const catchUp=body.enabled?await run(service,'catch_up'):null;return reply({result:changed.data,catchUp})}
   if(body.action==='run_overdue')return reply({result:await run(service,'manual')});
   if(body.action==='manual_trigger'){if(!['t24','feedback'].includes(body.eventType)||!body.bookingId)return reply({error:'Valid event type and booking are required'},400);const triggered=await user.rpc('v2_site_admin_manual_trigger_scheduled_event',{p_event_type:body.eventType,p_booking_id:body.bookingId});if(triggered.error)return reply({error:triggered.error.message},400);const scheduled=await service.rpc(body.eventType==='t24'?'v2_system_schedule_t24_journey_notifications':'v2_system_schedule_feedback_requests',body.eventType==='t24'?{p_as_of:deps.now()}:{p_as_of:deps.now(),p_limit:100});if(scheduled.error)return reply({error:scheduled.error.message},500);const emails=await deps.dispatchDueCustomerEmails(25);return reply({result:triggered.data,queued:scheduled.data,emails})}
   return reply({error:'Unknown action'},400);
  }catch(error){return reply({error:safeError(error)},500)}
 };
}
